// examples/svelte-ts/src/routes/scroll-area/basic/+page.svelte
<script lang="ts">
  import * as scrollArea from "@zag-js/scroll-area"
  import { normalizeProps, useMachine } from "@zag-js/svelte"
  import Toolbar from "$lib/components/toolbar.svelte"
  import StateVisualizer from "$lib/components/state-visualizer.svelte"
  import "@styles/scroll-area.css"

  const id = $props.id()
  const service = useMachine(scrollArea.machine, { id })

  const api = $derived(scrollArea.connect(service, normalizeProps))
</script>

<main class="scroll-area">
  <button onclick={() => api.scrollToEdge({ edge: "bottom" })}>Scroll to bottom</button>
  <div {...api.getRootProps()}>
    <div {...api.getViewportProps()}>
      <div {...api.getContentProps()}>
        {#each Array.from({ length: 100 }) as _, index}
          <div>{index}</div>
        {/each}
      </div>
    </div>
    {#if api.hasOverflowY}
      <div {...api.getScrollbarProps()}>
        <div {...api.getThumbProps()}></div>
      </div>
    {/if}
  </div>
</main>

<Toolbar>
  <StateVisualizer state={service} />
</Toolbar>

// examples/preact-ts/src/pages/scroll-area/basic.tsx
import { normalizeProps, useMachine } from "@zag-js/preact"
import * as scrollArea from "@zag-js/scroll-area"
import { scrollAreaControls } from "@zag-js/shared"
import { useId } from "react"
import { StateVisualizer } from "../../components/state-visualizer"
import { Toolbar } from "../../components/toolbar"
import { useControls } from "../../hooks/use-controls"

export default function Page() {
  const controls = useControls(scrollAreaControls)

  const service = useMachine(scrollArea.machine, {
    id: useId(),
    ...controls.context,
  })

  const api = scrollArea.connect(service, normalizeProps)

  return (
    <>
      <main className="scroll-area">
        <button onClick={() => api.scrollToEdge({ edge: "bottom" })}>Scroll to bottom</button>
        <div {...api.getRootProps()}>
          <div {...api.getViewportProps()}>
            <div {...api.getContentProps()} style={{ minWidth: "800px" }}>
              {Array.from({ length: 100 }).map((_, index) => (
                <div key={index}>{index}</div>
              ))}
            </div>
          </div>
          {api.hasOverflowY && (
            <div {...api.getScrollbarProps({ orientation: "vertical" })}>
              <div {...api.getThumbProps({ orientation: "vertical" })} />
            </div>
          )}
          {api.hasOverflowX && (
            <div {...api.getScrollbarProps({ orientation: "horizontal" })}>
              <div {...api.getThumbProps({ orientation: "horizontal" })} />
            </div>
          )}
        </div>
      </main>

      <Toolbar controls={controls.ui}>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}
