// examples/solid-ts/src/routes/scroll-area/nested.tsx
import * as scrollArea from "@zag-js/scroll-area"
import { mergeProps, normalizeProps, useMachine } from "@zag-js/solid"
import { createMemo, createUniqueId, For, type JSX } from "solid-js"

function ScrollArea(props: { children: JSX.Element; style?: JSX.CSSProperties }) {
  const service = useMachine(scrollArea.machine, {
    id: createUniqueId(),
  })

  const api = createMemo(() => scrollArea.connect(service, normalizeProps))

  return (
    <div {...mergeProps(api().getRootProps(), { style: props.style })}>
      <div {...api().getViewportProps()}>
        <div {...api().getContentProps()}>{props.children}</div>
      </div>
      {api().hasOverflowY && (
        <div {...api().getScrollbarProps()}>
          <div {...api().getThumbProps()} />
        </div>
      )}
    </div>
  )
}

export default function Page() {
  return (
    <main class="scroll-area">
      <ScrollArea style={{ height: "500px", width: "800px" }}>
        <For each={Array.from({ length: 5 })}>
          {() => (
            <ScrollArea style={{ "max-height": "200px" }}>
              <For each={Array.from({ length: 100 })}>{(_, index) => <div>{index()}</div>}</For>
            </ScrollArea>
          )}
        </For>
      </ScrollArea>
    </main>
  )
}

// examples/preact-ts/src/pages/scroll-area/nested.tsx
import { mergeProps, normalizeProps, useMachine } from "@zag-js/preact"
import * as scrollArea from "@zag-js/scroll-area"
import { useId } from "react"

const ScrollArea = (props: React.ComponentProps<"div">) => {
  const { children, ...rest } = props
  const service = useMachine(scrollArea.machine, { id: useId() })
  const api = scrollArea.connect(service, normalizeProps)

  return (
    <div {...mergeProps(api.getRootProps(), rest)}>
      <div {...api.getViewportProps()}>
        <div {...api.getContentProps()}>{children}</div>
      </div>
      {api.hasOverflowY && (
        <div {...api.getScrollbarProps()}>
          <div {...api.getThumbProps()} />
        </div>
      )}
    </div>
  )
}

export default function Page() {
  return (
    <main className="scroll-area">
      <ScrollArea style={{ height: 500, width: 800 }}>
        {Array.from({ length: 5 }).map((_, index) => (
          <ScrollArea key={index} style={{ maxHeight: 200 }}>
            {Array.from({ length: 100 }).map((_, index) => (
              <div key={index}>{index}</div>
            ))}
          </ScrollArea>
        ))}
      </ScrollArea>
    </main>
  )
}
