// examples/solid-ts/src/pages/menu-options.tsx
import { injectGlobal } from "@emotion/css"
import * as Menu from "@ui-machines/menu"
import { normalizeProps, PropTypes, useMachine, useSetup } from "@ui-machines/solid"
import { menuStyle } from "../../../../shared/style"
import { menuOptionData as data } from "../../../../shared/data"
import { StateVisualizer } from "../components/state-visualizer"
import { createMemo, For } from "solid-js"

injectGlobal(menuStyle)

export default function Page() {
  const [state, send] = useMachine(
    Menu.machine.withContext({
      values: { order: "", type: [] },
      onValuesChange: console.log,
    }),
  )
  const ref = useSetup<HTMLButtonElement>({ send, id: "1" })
  const api = createMemo(() => Menu.connect<PropTypes>(state, send, normalizeProps))

  return (
    <>
      <div>
        <button className="menu__trigger" ref={ref} {...api().triggerProps}>
          Actions <span aria-hidden>▾</span>
        </button>
        <div {...api().positionerProps}>
          <div className="menu__content" {...api().contentProps}>
            <For each={data.order}>
              {(item) => {
                const opts = { type: "radio", name: "order", value: item.id } as const
                return (
                  <div className="menu__item" {...api().getOptionItemProps(opts)}>
                    {api().isOptionChecked(opts) ? "✅" : null} {item.label}
                  </div>
                )
              }}
            </For>
            <hr />
            <For each={data.type}>
              {(item) => {
                const opts = { type: "checkbox", name: "type", value: item.id } as const
                return (
                  <div className="menu__item" {...api().getOptionItemProps(opts)}>
                    {api().isOptionChecked(opts) ? "✅" : null} {item.label}
                  </div>
                )
              }}
            </For>
          </div>
        </div>
      </div>

      <StateVisualizer state={state} />
    </>
  )
}

// examples/vue-ts/src/pages/menu-options.tsx
import { injectGlobal } from "@emotion/css"
import * as Menu from "@ui-machines/menu"
import { normalizeProps, useMachine, useSetup, PropTypes } from "@ui-machines/vue"
import { computed, defineComponent, h, Fragment } from "vue"
import { menuStyle } from "../../../../shared/style"
import { menuOptionData as data } from "../../../../shared/data"
import { StateVisualizer } from "../components/state-visualizer"

injectGlobal(menuStyle)

export default defineComponent({
  name: "Menu",
  setup() {
    const [state, send] = useMachine(
      Menu.machine.withContext({
        values: { order: "", type: [] },
        onValuesChange: console.log,
      }),
    )

    const ref = useSetup({ send, id: "1" })

    const apiRef = computed(() => Menu.connect<PropTypes>(state.value, send, normalizeProps))

    return () => {
      const api = apiRef.value
      return (
        <>
          <div ref={ref}>
            <button class="menu__trigger" {...api.triggerProps}>
              Actions <span aria-hidden>▾</span>
            </button>
            <div {...api.positionerProps}>
              <div class="menu__content" {...api.contentProps}>
                {data.order.map((item) => {
                  const opts = { type: "radio", name: "order", value: item.id } as const
                  return (
                    <div key={item.id} class="menu__item" {...api.getOptionItemProps(opts)}>
                      {api.isOptionChecked(opts) ? "✅" : null} {item.label}
                    </div>
                  )
                })}
                <hr />
                {data.type.map((item) => {
                  const opts = { type: "checkbox", name: "type", value: item.id } as const
                  return (
                    <div key={item.id} class="menu__item" {...api.getOptionItemProps(opts)}>
                      {api.isOptionChecked(opts) ? "✅" : null} {item.label}
                    </div>
                  )
                })}
              </div>
            </div>
          </div>

          <StateVisualizer state={state} />
        </>
      )
    }
  },
})
