// examples/nuxt-ts/app/pages/toc/indicator.vue
<script setup lang="ts">
import styles from "../../../../../shared/src/css/toc.module.css"
import * as toc from "@zag-js/toc"
import { tocControls, tocData } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/vue"

const controls = useControls(tocControls)

const service = useMachine(
  toc.machine,
  controls.mergeProps<toc.Props>({
    id: useId(),
    items: tocData,
  }),
)

const api = computed(() => toc.connect(service, normalizeProps))
</script>

<template>
  <main class="toc">
    <div style="display: flex; gap: 2rem">
      <nav v-bind="api.getRootProps()" :class="styles.Root">
        <h5 v-bind="api.getTitleProps()" :class="styles.Title">On this page</h5>
        <ul v-bind="api.getListProps()" :class="styles.List">
          <div v-bind="api.getIndicatorProps()" :class="styles.Indicator" />
          <li
            v-for="item in tocData"
            :key="item.value"
            v-bind="api.getItemProps({ item })" :class="styles.Item"
          >
            <a
              :href="`#${item.value}`"
              v-bind="api.getLinkProps({ item })" :class="styles.Link"
            >
              {{ item.label }}
            </a>
          </li>
        </ul>
      </nav>

      <div style="max-height: 20rem; overflow: auto; flex: 1">
        <div v-for="item in tocData" :key="item.value" style="margin-bottom: 1rem">
          <h2 :id="item.value" :style="{ fontSize: item.depth === 2 ? '1.25rem' : '1rem' }">
            {{ item.label }}
          </h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.
          </p>
        </div>
      </div>
    </div>
  </main>

  <Toolbar>
    <StateVisualizer :state="service" />
  </Toolbar>
</template>

// examples/next-ts/pages/toc/indicator.tsx
import styles from "../../../../shared/src/css/toc.module.css"
import { normalizeProps, useMachine } from "@zag-js/react"
import { tocControls, tocData } from "@zag-js/shared"
import * as toc from "@zag-js/toc"
import { useId } from "react"
import { StateVisualizer } from "../../components/state-visualizer"
import { Toolbar } from "../../components/toolbar"
import { useControls } from "../../hooks/use-controls"

export default function Page() {
  const controls = useControls(tocControls)

  const service = useMachine(toc.machine, {
    id: useId(),
    items: tocData,
    ...controls.context,
  })

  const api = toc.connect(service, normalizeProps)

  return (
    <>
      <main className="toc">
        <div style={{ display: "flex", gap: "2rem" }}>
          <nav {...api.getRootProps()} className={styles.Root}>
            <h5 {...api.getTitleProps()} className={styles.Title}>On this page</h5>
            <ul {...api.getListProps()} className={styles.List}>
              <div {...api.getIndicatorProps()} className={styles.Indicator} />
              {tocData.map((item) => (
                <li key={item.value} {...api.getItemProps({ item })} className={styles.Item}>
                  <a href={`#${item.value}`} {...api.getLinkProps({ item })} className={styles.Link}>
                    {item.label}
                  </a>
                </li>
              ))}
            </ul>
          </nav>

          <div style={{ maxHeight: "20rem", overflow: "auto", flex: 1 }}>
            {tocData.map((item) => (
              <div key={item.value} style={{ marginBottom: "1rem" }}>
                <h2 id={item.value} style={{ fontSize: item.depth === 2 ? "1.25rem" : "1rem" }}>
                  {item.label}
                </h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
                  dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.
                </p>
              </div>
            ))}
          </div>
        </div>
      </main>

      <Toolbar controls={controls.ui}>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}
