// examples/next-ts/app/tooltip/default-open/page.tsx
"use client"

import { normalizeProps, Portal, useMachine } from "@zag-js/react"
import * as tooltip from "@zag-js/tooltip"
import { StateVisualizer } from "@/components/state-visualizer"
import { Toolbar } from "@/components/toolbar"
import { Presence } from "@/components/presence"
import "@styles/tooltip.css"

export default function Page() {
  const id = "tip-1"
  const id2 = "tip-2"
  const service = useMachine(tooltip.machine, { id, defaultOpen: true })
  const service2 = useMachine(tooltip.machine, { id: id2, defaultOpen: true })

  const api = tooltip.connect(service, normalizeProps)
  const api2 = tooltip.connect(service2, normalizeProps)
  return (
    <>
      <main className="tooltip">
        <div className="root">
          <>
            <button data-testid={`${id}-trigger`} {...api.getTriggerProps()}>
              Hover me
            </button>
            <Portal>
              <div {...api.getPositionerProps()}>
                <Presence className="tooltip-content" data-testid={`${id}-tooltip`} {...api.getContentProps()}>
                  Tooltip
                </Presence>
              </div>
            </Portal>
          </>
          <button data-testid={`${id2}-trigger`} {...api2.getTriggerProps()}>
            Over me
          </button>
          <Portal>
            <div {...api2.getPositionerProps()}>
              <Presence className="tooltip-content" data-testid={`${id2}-tooltip`} {...api2.getContentProps()}>
                Tooltip 2
              </Presence>
            </div>
          </Portal>
        </div>
      </main>
      <Toolbar controls={null}>
        <StateVisualizer state={service} label="Tooltip 1" />
        <StateVisualizer state={service2} label="Tooltip 2" />
      </Toolbar>
    </>
  )
}

// examples/svelte-ts/src/routes/tooltip/default-open/+page.svelte
<script lang="ts">
  import StateVisualizer from "$lib/components/state-visualizer.svelte"
  import Toolbar from "$lib/components/toolbar.svelte"
  import { normalizeProps, useMachine, portal } from "@zag-js/svelte"
  import * as tooltip from "@zag-js/tooltip"
  import "@styles/tooltip.css"

  const id = "tip-1"
  const id2 = "tip-2"

  const service = useMachine(tooltip.machine, { id, defaultOpen: true })
  const service2 = useMachine(tooltip.machine, { id: id2, defaultOpen: true })

  const api = $derived(tooltip.connect(service, normalizeProps))
  const api2 = $derived(tooltip.connect(service2, normalizeProps))
</script>

<main class="tooltip">
  <div class="root">
    <button data-testid={`${id}-trigger`} {...api.getTriggerProps()}> Hover me </button>
    {#if api.open}
      <div {...api.getPositionerProps()}>
        <div class="tooltip-content" data-testid={`${id}-tooltip`} {...api.getContentProps()}>Tooltip</div>
      </div>
    {/if}
    <button data-testid={`${id2}-trigger`} {...api2.getTriggerProps()}> Over me </button>
    {#if api2.open}
      <div use:portal {...api2.getPositionerProps()}>
        <div class="tooltip-content" data-testid={`${id2}-tooltip`} {...api2.getContentProps()}>Tooltip 2</div>
      </div>
    {/if}
  </div>
</main>

<Toolbar controls={null}>
  <StateVisualizer state={service} label="Tooltip 1" />
  <StateVisualizer state={service2} label="Tooltip 2" />
</Toolbar>
