// examples/next-ts/pages/drawer/action-sheet.tsx
import * as drawer from "@zag-js/drawer"
import { normalizeProps, useMachine } from "@zag-js/react"
import { useId } from "react"
import { Presence } from "../../components/presence"
import styles from "../../../shared/styles/drawer-action-sheet.module.css"

export default function Page() {
  const service = useMachine(drawer.machine, {
    id: useId(),
  })

  const api = drawer.connect(service, normalizeProps)

  return (
    <main>
      <button className={styles.trigger} {...api.getTriggerProps()}>
        Manage Profile
      </button>
      <Presence className={styles.backdrop} {...api.getBackdropProps()} />
      <div className={styles.positioner} {...api.getPositionerProps()}>
        <Presence className={styles.popup} {...api.getContentProps({ draggable: false })}>
          <div className={styles.surface}>
            <div {...api.getTitleProps()} className={styles.title}>
              Profile Actions
            </div>
            <ul className={styles.actions}>
              <li className={styles.action}>
                <button className={styles.actionButton} onClick={() => api.setOpen(false)}>
                  Edit Profile
                </button>
              </li>
              <li className={styles.action}>
                <button className={styles.actionButton} onClick={() => api.setOpen(false)}>
                  Change Avatar
                </button>
              </li>
              <li className={styles.action}>
                <button className={styles.actionButton} onClick={() => api.setOpen(false)}>
                  Privacy Settings
                </button>
              </li>
            </ul>
          </div>

          <div className={styles.dangerSurface}>
            <button className={styles.dangerButton} onClick={() => api.setOpen(false)}>
              Delete Account
            </button>
          </div>

          <div className={styles.surface}>
            <button className={styles.actionButton} {...api.getCloseTriggerProps()}>
              Cancel
            </button>
          </div>
        </Presence>
      </div>
    </main>
  )
}

// examples/solid-ts/src/routes/drawer/action-sheet.tsx
import * as drawer from "@zag-js/drawer"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { createMemo, createUniqueId } from "solid-js"
import { Presence } from "../../components/presence"
import styles from "../../../../shared/styles/drawer-action-sheet.module.css"

export default function Page() {
  const service = useMachine(drawer.machine, () => ({
    id: createUniqueId(),
  }))

  const api = createMemo(() => drawer.connect(service, normalizeProps))

  return (
    <main>
      <button {...api().getTriggerProps()} class={styles.trigger}>
        Manage Profile
      </button>
      <Presence {...api().getBackdropProps()} class={styles.backdrop} />
      <div {...api().getPositionerProps()} class={styles.positioner}>
        <Presence {...api().getContentProps({ draggable: false })} class={styles.popup}>
          <div class={styles.surface}>
            <div {...api().getTitleProps()} class={styles.title}>
              Profile Actions
            </div>
            <ul class={styles.actions}>
              <li class={styles.action}>
                <button type="button" class={styles.actionButton} onClick={() => api().setOpen(false)}>
                  Edit Profile
                </button>
              </li>
              <li class={styles.action}>
                <button type="button" class={styles.actionButton} onClick={() => api().setOpen(false)}>
                  Change Avatar
                </button>
              </li>
              <li class={styles.action}>
                <button type="button" class={styles.actionButton} onClick={() => api().setOpen(false)}>
                  Privacy Settings
                </button>
              </li>
            </ul>
          </div>

          <div class={styles.dangerSurface}>
            <button type="button" class={styles.dangerButton} onClick={() => api().setOpen(false)}>
              Delete Account
            </button>
          </div>

          <div class={styles.surface}>
            <button type="button" {...api().getCloseTriggerProps()} class={styles.actionButton}>
              Cancel
            </button>
          </div>
        </Presence>
      </div>
    </main>
  )
}
