// examples/vue-ts/src/components/iframe.tsx
import { Teleport, computed, defineComponent, ref } from "vue"

export const IFrame = defineComponent({
  setup(_, { attrs, slots }) {
    const frameRef = ref<HTMLIFrameElement>()
    const mountNodeRef = computed(() => frameRef.value?.contentWindow?.document.body)
    return () => {
      const mountNode = mountNodeRef.value
      return (
        <iframe title="frame" ref={frameRef} {...attrs}>
          {mountNode ? <Teleport to={mountNode}>{slots.default?.()}</Teleport> : null}
        </iframe>
      )
    }
  },
})

// examples/preact-ts/src/components/iframe.tsx
import { useId, useState } from "react"
import { createPortal } from "react-dom"

type IFrameProps = React.ComponentProps<"iframe">

export const IFrame = function IFrame(props: IFrameProps) {
  const { children, ...rest } = props

  const [frameRef, setFrameRef] = useState<HTMLIFrameElement | null>(null)
  const mountNode = frameRef?.contentWindow?.document.body

  return (
    <iframe title={`frame:${useId()}`} ref={setFrameRef} {...rest}>
      {mountNode ? createPortal(children, mountNode) : null}
    </iframe>
  )
}
