// examples/next-ts/app/floating-panel/popover-inside/page.tsx
"use client"

import * as floating from "@zag-js/floating-panel"
import * as popover from "@zag-js/popover"
import { normalizeProps, useMachine } from "@zag-js/react"
import { ArrowDownLeft, Maximize2, Minus, XIcon } from "lucide-react"
import { useId } from "react"
import { StateVisualizer } from "@/components/state-visualizer"
import { Toolbar } from "@/components/toolbar"
import "@styles/floating-panel.css"
import "@styles/popover.css"

export default function Page() {
  const service = useMachine(floating.machine, {
    id: useId(),
    closeOnEscape: true,
    defaultSize: { width: 400, height: 300 },
  })

  const api = floating.connect(service, normalizeProps)

  return (
    <>
      <main className="floating-panel">
        <div>
          <button {...api.getTriggerProps()}>Toggle Panel</button>
          <div {...api.getPositionerProps()}>
            <div {...api.getContentProps()}>
              <div {...api.getDragTriggerProps()}>
                <div {...api.getHeaderProps()}>
                  <p {...api.getTitleProps()}>Floating Panel (Nested Popover)</p>
                  <div {...api.getControlProps()}>
                    <button {...api.getStageTriggerProps({ stage: "minimized" })}>
                      <Minus />
                    </button>
                    <button {...api.getStageTriggerProps({ stage: "maximized" })}>
                      <Maximize2 />
                    </button>
                    <button {...api.getStageTriggerProps({ stage: "default" })}>
                      <ArrowDownLeft />
                    </button>
                    <button {...api.getCloseTriggerProps()}>
                      <XIcon />
                    </button>
                  </div>
                </div>
              </div>
              <div {...api.getBodyProps()}>
                <p>Escape closes the popover first, then the panel.</p>
                <Popover />
              </div>

              {floating.resizeTriggerPlacements.map((placement) => (
                <div key={placement} {...api.getResizeTriggerProps({ placement })} />
              ))}
            </div>
          </div>
        </div>
      </main>

      <Toolbar>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}

function Popover() {
  const service = useMachine(popover.machine, {
    id: useId(),
  })

  const api = popover.connect(service, normalizeProps)

  return (
    <div>
      <button {...api.getTriggerProps()}>Open Popover</button>
      <div {...api.getPositionerProps()}>
        <div {...api.getContentProps()}>
          <div {...api.getTitleProps()}>Nested Popover</div>
          <div {...api.getDescriptionProps()}>Press Escape to close this popover without closing the panel.</div>
          <button {...api.getCloseTriggerProps()}>Close Popover</button>
        </div>
      </div>
    </div>
  )
}

// examples/solid-ts/src/routes/floating-panel/popover-inside.tsx
import * as floatingPanel from "@zag-js/floating-panel"
import * as popover from "@zag-js/popover"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { ArrowDownLeft, Maximize2, Minus, XIcon } from "lucide-solid"
import { For, createMemo, createUniqueId } from "solid-js"
import { StateVisualizer } from "~/components/state-visualizer"
import { Toolbar } from "~/components/toolbar"
import "@styles/floating-panel.css"

export default function Page() {
  const service = useMachine(floatingPanel.machine, {
    id: createUniqueId(),
    closeOnEscape: true,
    defaultSize: { width: 400, height: 300 },
  })

  const api = createMemo(() => floatingPanel.connect(service, normalizeProps))

  return (
    <>
      <main class="floating-panel">
        <div>
          <button {...api().getTriggerProps()}>Toggle Panel</button>
          <div {...api().getPositionerProps()}>
            <div {...api().getContentProps()}>
              <div {...api().getDragTriggerProps()}>
                <div {...api().getHeaderProps()}>
                  <p {...api().getTitleProps()}>Floating Panel (Nested Popover)</p>
                  <div {...api().getControlProps()}>
                    <button {...api().getStageTriggerProps({ stage: "minimized" })}>
                      <Minus />
                    </button>
                    <button {...api().getStageTriggerProps({ stage: "maximized" })}>
                      <Maximize2 />
                    </button>
                    <button {...api().getStageTriggerProps({ stage: "default" })}>
                      <ArrowDownLeft />
                    </button>
                    <button {...api().getCloseTriggerProps()}>
                      <XIcon />
                    </button>
                  </div>
                </div>
              </div>
              <div {...api().getBodyProps()}>
                <p>Escape closes the popover first, then the panel.</p>
                <Popover />
              </div>

              <For each={floatingPanel.resizeTriggerPlacements}>
                {(placement) => <div {...api().getResizeTriggerProps({ placement })} />}
              </For>
            </div>
          </div>
        </div>
      </main>

      <Toolbar>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}

function Popover() {
  const service = useMachine(popover.machine, {
    id: createUniqueId(),
  })

  const api = createMemo(() => popover.connect(service, normalizeProps))

  return (
    <div>
      <button {...api().getTriggerProps()}>Open Popover</button>
      <div {...api().getPositionerProps()}>
        <div {...api().getContentProps()}>
          <div {...api().getTitleProps()}>Nested Popover</div>
          <div {...api().getDescriptionProps()}>Press Escape to close this popover without closing the panel.</div>
          <button {...api().getCloseTriggerProps()}>Close Popover</button>
        </div>
      </div>
    </div>
  )
}
