// examples/preact-ts/src/pages/number-input/scrubber.tsx
import * as numberInput from "@zag-js/number-input"
import { normalizeProps, useMachine } from "@zag-js/preact"
import { numberInputControls } from "@zag-js/shared"
import { MoveHorizontalIcon } from "lucide-preact"
import { useId } from "react"
import { useControls } from "../../hooks/use-controls"
import { Toolbar } from "../../components/toolbar"
import { StateVisualizer } from "../../components/state-visualizer"
import "@styles/number-input.css"

export default function NumberInput() {
  const controls = useControls(numberInputControls)

  const service = useMachine(numberInput.machine, {
    id: useId(),
    ...controls.context,
  })

  const api = numberInput.connect(service, normalizeProps)

  return (
    <>
      <main>
        <div {...api.getRootProps()}>
          <div data-testid="scrubber" {...api.getScrubberProps()}>
            <span {...api.getScrubberCursorProps()}>
              <MoveHorizontalIcon />
            </span>
          </div>
          <label data-testid="label" {...api.getLabelProps()}>
            Enter number:
          </label>
          <div {...api.getControlProps()}>
            <button data-testid="dec-button" {...api.getDecrementTriggerProps()}>
              DEC
            </button>
            <input data-testid="input" {...api.getInputProps()} />
            <button data-testid="inc-button" {...api.getIncrementTriggerProps()}>
              INC
            </button>
          </div>
        </div>
      </main>

      <Toolbar controls={controls.ui}>
        <StateVisualizer state={service} omit={["formatter", "parser"]} />
      </Toolbar>
    </>
  )
}

// examples/solid-ts/src/routes/number-input/scrubber.tsx
import * as numberInput from "@zag-js/number-input"
import { numberInputControls } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { MoveHorizontalIcon } from "lucide-solid"
import { createMemo, createUniqueId } from "solid-js"
import { StateVisualizer } from "~/components/state-visualizer"
import { Toolbar } from "~/components/toolbar"
import { useControls } from "~/hooks/use-controls"
import "@styles/number-input.css"

export default function Page() {
  const controls = useControls(numberInputControls)

  const service = useMachine(numberInput.machine, controls.mergeProps({ id: createUniqueId() }))

  const api = createMemo(() => numberInput.connect(service, normalizeProps))

  return (
    <>
      <main>
        <div {...api().getRootProps()}>
          <div data-testid="scrubber" {...api().getScrubberProps()}>
            <span {...api().getScrubberCursorProps()}>
              <MoveHorizontalIcon />
            </span>
          </div>
          <label data-testid="label" {...api().getLabelProps()}>
            Enter number:
          </label>
          <div {...api().getControlProps()}>
            <button data-testid="dec-button" {...api().getDecrementTriggerProps()}>
              DEC
            </button>
            <input data-testid="input" {...api().getInputProps()} />
            <button data-testid="inc-button" {...api().getIncrementTriggerProps()}>
              INC
            </button>
          </div>
        </div>
      </main>

      <Toolbar controls={controls}>
        <StateVisualizer state={service} omit={["formatter", "parser"]} />
      </Toolbar>
    </>
  )
}
