// examples/svelte-ts/src/routes/image-cropper-fixed/+page.svelte
<script lang="ts">
  import StateVisualizer from "$lib/components/state-visualizer.svelte"
  import Toolbar from "$lib/components/toolbar.svelte"
  import { useControls } from "$lib/use-controls.svelte"
  import * as imageCropper from "@zag-js/image-cropper"
  import { imageCropperControls } from "@zag-js/shared"
  import { normalizeProps, useMachine } from "@zag-js/svelte"

  const controls = useControls(imageCropperControls)

  let zoom = $state(1)
  let rotation = $state(0)

  const id = $props.id()
  const service = useMachine(
    imageCropper.machine,
    controls.mergeProps<imageCropper.Props>({
      id,
      get zoom() {
        return zoom
      },
      onZoomChange(details) {
        zoom = details.zoom
      },
      get rotation() {
        return rotation
      },
      onRotationChange(details) {
        rotation = details.rotation
      },
      fixedCropArea: true,
    }),
  )

  const api = $derived(imageCropper.connect(service, normalizeProps))
</script>

<main class="image-cropper">
  <div {...api.getRootProps()}>
    <div {...api.getViewportProps()}>
      <img src="https://picsum.photos/seed/a/500/300" {...api.getImageProps()} alt="Cropper" />
      <div {...api.getSelectionProps()}>
        <div {...api.getOverlayProps()}></div>
      </div>
    </div>
  </div>
  <label>
    Zoom:
    <input
      type="range"
      min={service.prop("minZoom")}
      max={service.prop("maxZoom")}
      step={service.prop("zoomStep")}
      value={zoom}
      oninput={(e) => api.setZoom(Number(e.currentTarget.value))}
    />
  </label>
  <label>
    Rotation:
    <input
      type="range"
      min={0}
      max={360}
      step={1}
      value={rotation}
      oninput={(e) => api.setRotation(Number(e.currentTarget.value))}
    />
  </label>
</main>

<Toolbar {controls}>
  <StateVisualizer state={service} context={["naturalSize", "crop", "zoom", "rotation", "offset"]} />
</Toolbar>

// examples/solid-ts/src/routes/image-cropper-fixed.tsx
import * as imageCropper from "@zag-js/image-cropper"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { imageCropperControls } from "@zag-js/shared"
import { createMemo, createSignal, createUniqueId } from "solid-js"
import { StateVisualizer } from "~/components/state-visualizer"
import { Toolbar } from "~/components/toolbar"
import { useControls } from "~/hooks/use-controls"

export default function Page() {
  const controls = useControls(imageCropperControls)
  const [zoom, setZoom] = createSignal(1)
  const [rotation, setRotation] = createSignal(0)

  const service = useMachine(
    imageCropper.machine,
    controls.mergeProps<imageCropper.Props>(() => ({
      id: createUniqueId(),
      zoom: zoom(),
      onZoomChange(details) {
        setZoom(details.zoom)
      },
      rotation: rotation(),
      onRotationChange(details) {
        setRotation(details.rotation)
      },
      fixedCropArea: true,
    })),
  )

  const api = createMemo(() => imageCropper.connect(service, normalizeProps))

  return (
    <>
      <main class="image-cropper">
        <div {...api().getRootProps()}>
          <div {...api().getViewportProps()}>
            <img src="https://picsum.photos/seed/a/500/300" {...api().getImageProps()} />
            <div {...api().getSelectionProps()}>
              <div {...api().getOverlayProps()} />
            </div>
          </div>
        </div>
        <label>
          Zoom:
          <input
            type="range"
            min={service.prop("minZoom")}
            max={service.prop("maxZoom")}
            step={service.prop("zoomStep")}
            value={zoom()}
            onInput={(e) => api().setZoom(Number(e.currentTarget.value))}
          />
        </label>
        <label>
          Rotation:
          <input
            type="range"
            min={0}
            max={360}
            step={1}
            value={rotation()}
            onInput={(e) => api().setRotation(Number(e.currentTarget.value))}
          />
        </label>
      </main>

      <Toolbar controls={controls}>
        <StateVisualizer state={service} context={["naturalSize", "crop", "zoom", "rotation", "offset"]} />
      </Toolbar>
    </>
  )
}
