// examples/svelte-ts/src/routes/+page.svelte
<script lang="ts">
  import { componentRoutesData } from "@zag-js/shared"
</script>

<div class="index-nav">
  <h2>Svelte UI Machines</h2>
  <ul>
    {#each componentRoutesData as component}
      <li>
        <a href={`/${component.slug}`}>{component.label}</a>
      </li>
    {/each}
  </ul>
</div>

// examples/solid-ts/src/routes/index.tsx
import { componentRoutesData } from "@zag-js/shared"
import { A } from "@solidjs/router"
import { For } from "solid-js/web"

export default function Home() {
  return (
    <div class="index-nav">
      <h2>Zag.js + Solid</h2>
      <ul>
        <For each={componentRoutesData}>
          {(component) => (
            <li>
              <A href={`/${component.slug}`}>{component.label}</A>
            </li>
          )}
        </For>
      </ul>
    </div>
  )
}
