// examples/nuxt-ts/pages/popper.vue
<script setup lang="ts">
import { getPlacement, getPlacementStyles } from "@zag-js/popper"
import { ref, onMounted, computed } from "vue"

const referenceRef = ref<HTMLButtonElement | null>(null)
const floatingRef = ref<HTMLDivElement | null>(null)
const positioned = ref({})

onMounted(() => {
  if (!referenceRef.value || !floatingRef.value) return
  return getPlacement(referenceRef.value, floatingRef.value, {
    placement: "right-start",
    onComplete(data) {
      positioned.value = data
    },
  })
})

const styles = computed(() => getPlacementStyles(positioned.value))
</script>

<template>
  <main>
    <button ref="referenceRef">Hello StackBlitz!</button>
    <div :style="styles.floating" ref="floatingRef">Start editing to see some magic happen :)</div>
  </main>
</template>

// examples/solid-ts/src/routes/popper.tsx
import { getPlacement, getPlacementStyles } from "@zag-js/popper"
import { createSignal, onCleanup, onMount } from "solid-js"

export default function Page() {
  let referenceRef: HTMLButtonElement | undefined
  let floatingRef: HTMLDivElement | undefined
  const [positioned, setPositioned] = createSignal({})

  onMount(() => {
    if (!referenceRef || !floatingRef) return
    const cleanup = getPlacement(referenceRef, floatingRef, {
      placement: "right-start",
      onComplete(data) {
        setPositioned(data)
      },
    })
    onCleanup(() => cleanup?.())
  })

  const styles = () => getPlacementStyles(positioned())

  return (
    <div>
      <button ref={referenceRef}>Hello StackBlitz!</button>
      <div style={styles().floating} ref={floatingRef}>
        Start editing to see some magic happen :)
      </div>
    </div>
  )
}
