// examples/nuxt-ts/app/pages/angle-slider/color-wheel.vue
<script setup lang="ts">
import * as angleSlider from "@zag-js/angle-slider"
import { normalizeProps, useMachine } from "@zag-js/vue"
import "@styles/angle-slider-custom.css"

const id = useId()
const service = useMachine(angleSlider.machine, computed(() => ({ id, defaultValue: 0 })))
const api = computed(() => angleSlider.connect(service, normalizeProps))
</script>

<template>
  <main class="angle-slider angle-slider-color-wheel">
    <h1>Angle Slider — Color Wheel (Hue)</h1>
    <div class="swatch" :style="{ background: `hsl(${api.value} 100% 50%)` }" />
    <div v-bind="api.getRootProps()">
      <label v-bind="api.getLabelProps()">
        Hue:
        <div v-bind="api.getValueTextProps()">{{ api.value }}°</div>
      </label>
      <div v-bind="api.getControlProps()">
        <div v-bind="api.getThumbProps()"></div>
      </div>
      <input v-bind="api.getHiddenInputProps()" />
    </div>
  </main>
</template>

// examples/next-ts/app/angle-slider/color-wheel/page.tsx
"use client"

import * as angleSlider from "@zag-js/angle-slider"
import { normalizeProps, useMachine } from "@zag-js/react"
import { useId } from "react"
import "@styles/angle-slider-custom.css"

export default function Page() {
  const service = useMachine(angleSlider.machine, {
    id: useId(),
    defaultValue: 0,
  })

  const api = angleSlider.connect(service, normalizeProps)

  const color = `hsl(${api.value} 100% 50%)`

  return (
    <main className="angle-slider angle-slider-color-wheel">
      <h1>Angle Slider — Color Wheel (Hue)</h1>

      <div className="swatch" style={{ background: color }} />

      <div {...api.getRootProps()}>
        <label {...api.getLabelProps()}>
          Hue: <div {...api.getValueTextProps()}>{api.value}°</div>
        </label>
        <div {...api.getControlProps()}>
          <div {...api.getThumbProps()}></div>
        </div>
        <input {...api.getHiddenInputProps()} />
      </div>
    </main>
  )
}
