// examples/alpine-ts/server/components/iframe.tsx
export function IFrame(props: any) {
  return (
    <>
      <iframe x-bind:title="$id('frame')" x-ref="frame" {...props}></iframe>
      <template
        x-init="Array.from($el.content.cloneNode(true).children).forEach((child) =>
          $refs.frame.contentWindow.document.body.appendChild(child))"
      >
        <slot />
      </template>
    </>
  )
}

// examples/svelte-ts/src/lib/components/iframe.svelte
<script lang="ts">
  import { portal } from "@zag-js/svelte"
  import { onMount } from "svelte"

  let frameRef: HTMLIFrameElement | null = null
  let mountNode = $state<HTMLElement | undefined>()

  onMount(() => {
    if (!frameRef) return
    mountNode = frameRef.contentWindow?.document.body
  })
</script>

<iframe title="iframe" bind:this={frameRef}>
  {#if mountNode}
    <span use:portal={{ container: mountNode }}>
      <slot />
    </span>
  {/if}
</iframe>
