// examples/next-ts/components/sidebar.tsx
"use client"

import { createFilter } from "@zag-js/i18n-utils"
import { normalizeProps, useMachine } from "@zag-js/react"
import { sidebarTree, type SidebarNode } from "@zag-js/shared"
import * as tree from "@zag-js/tree-view"
import { ChevronRightIcon, SearchIcon, XIcon } from "lucide-react"
import Link from "next/link"
import { usePathname, useSearchParams } from "next/navigation"
import { JSX, useEffect, useId, useMemo, useState } from "react"
import styles from "@styles/sidebar.module.css"

export function Sidebar() {
  const pathname = usePathname() || "/"
  const searchParams = useSearchParams()

  const selectedFromParam = searchParams.get("selected")
  const selectedFromPath = getActiveValueFromPath(pathname)
  const activeValue = selectedFromParam || selectedFromPath
  const activeBranch = activeValue?.split("/")[0]

  const expandedRaw = searchParams.get("expanded")
  const expandedFromUrl = useMemo(() => {
    if (expandedRaw == null) return activeBranch ? [activeBranch] : []
    return expandedRaw ? expandedRaw.split(",").filter(Boolean) : []
  }, [expandedRaw, activeBranch])

  // URL only grows on expand; collapses stay local so they don't write history entries.
  const [localExpanded, setLocalExpanded] = useState<string[] | null>(null)
  const expandedValue = localExpanded ?? expandedFromUrl

  const expandedKey = expandedFromUrl.join("|")
  useEffect(() => {
    setLocalExpanded(null)
  }, [expandedKey])

  const [query, setQuery] = useState("")

  const collection = useMemo(() => {
    const trimmed = query.trim()
    if (!trimmed) return baseCollection
    const keep = new Set<string>()
    sidebarTree.children?.forEach((child) => collectKeepSet(child, trimmed, false, keep))
    return baseCollection.filter((node) => keep.has(node.id))
  }, [query])

  // Search expansion is local-only — searching shouldn't pollute the URL.
  const [searchExpanded, setSearchExpanded] = useState<string[] | null>(null)
  useEffect(() => {
    if (!query.trim()) {
      setSearchExpanded(null)
      return
    }
    setSearchExpanded(collection.getBranchValues())
  }, [query, collection])

  const machineExpanded = searchExpanded ?? expandedValue

  const service = useMachine(tree.machine, {
    id: useId(),
    collection,
    selectedValue: activeValue ? [activeValue] : [],
    expandedValue: machineExpanded,
    onExpandedChange: (details) => {
      if (query.trim()) {
        setSearchExpanded(details.expandedValue)
        return
      }
      setLocalExpanded(details.expandedValue)
    },
  })

  const api = tree.connect(service, normalizeProps)

  return (
    <aside className={styles.sidebar}>
      <header className={styles.header}>
        <strong>Zagjs</strong>
      </header>

      <div className={styles.search}>
        <SearchIcon size={14} aria-hidden />
        <input
          type="search"
          placeholder="Find component"
          value={query}
          onChange={(event) => setQuery(event.target.value)}
        />
        {query && (
          <button type="button" className={styles.clear} aria-label="Clear search" onClick={() => setQuery("")}>
            <XIcon size={14} />
          </button>
        )}
      </div>

      <div {...api.getRootProps()} className={styles.tree}>
        <div {...api.getTreeProps()}>
          {collection.rootNode.children?.length ? (
            collection.rootNode.children.map((node, index) => (
              <TreeNode
                key={node.id}
                node={node}
                indexPath={[index]}
                api={api}
                expanded={machineExpanded}
                selected={activeValue}
              />
            ))
          ) : (
            <p className={styles.empty}>No matches</p>
          )}
        </div>
      </div>
    </aside>
  )
}

interface TreeNodeProps {
  node: SidebarNode
  indexPath: number[]
  api: tree.Api
  expanded: string[]
  selected: string | null
}

function TreeNode(props: TreeNodeProps): JSX.Element {
  const { node, indexPath, api, expanded, selected } = props
  const nodeProps = { indexPath, node }
  const nodeState = api.getNodeState(nodeProps)

  // Branch href targets its first leaf and bakes the branch into `?expanded=` so one navigation does it all.
  const target = node.href ? node : node.children?.find((c) => c.href)
  const nextExpanded = nodeState.isBranch && !expanded.includes(node.id) ? [...expanded, node.id] : expanded
  const href = target?.href ? `${target.href}${buildSearch(target.id, nextExpanded)}` : "#"

  return (
    <div {...api.getNodeGroupProps(nodeProps)}>
      <Link href={href} {...api.getNodeProps(nodeProps)}>
        <div {...api.getCellProps(nodeProps)}>
          {nodeState.isBranch && (
            <span {...api.getNodeIndicatorProps({ ...nodeProps, type: "expanded" })} className={styles.chevron}>
              <ChevronRightIcon size={14} />
            </span>
          )}
          <span {...api.getNodeTextProps(nodeProps)} className={styles.label}>
            {node.name}
          </span>
        </div>
      </Link>
      {nodeState.isBranch && (
        <div {...api.getNodeGroupContentProps(nodeProps)}>
          {node.children?.map((child, index) => (
            <TreeNode
              key={child.id}
              node={child}
              indexPath={[...indexPath, index]}
              api={api}
              expanded={expanded}
              selected={selected}
            />
          ))}
        </div>
      )}
    </div>
  )
}

const baseCollection = tree.collection<SidebarNode>({
  nodeToValue: (node) => node.id,
  nodeToString: (node) => node.name,
  rootNode: sidebarTree,
})

const filter = createFilter({ sensitivity: "base" })

// Mark a node as a keeper if it OR any ancestor matches; needed because `collection.filter`
// alone would prune children of a matched branch when the children don't themselves match.
function collectKeepSet(node: SidebarNode, query: string, ancestorMatched: boolean, keep: Set<string>): boolean {
  const selfMatched = ancestorMatched || filter.contains(node.name, query)
  let anyChildKept = false
  for (const child of node.children ?? []) {
    if (collectKeepSet(child, query, selfMatched, keep)) anyChildKept = true
  }
  if (selfMatched || anyChildKept) {
    keep.add(node.id)
    return true
  }
  return false
}

function getActiveValueFromPath(pathname: string): string | null {
  const segments = pathname.split("/").filter(Boolean)
  if (segments.length < 2) return null
  return `${segments[0]}/${segments[1]}`
}

function buildSearch(selected: string | null, expanded: string[]): string {
  const params = new URLSearchParams()
  if (selected) params.set("selected", selected)
  if (expanded.length) params.set("expanded", expanded.join(","))
  const out = params.toString()
  return out ? `?${out}` : ""
}

// examples/svelte-ts/src/lib/components/sidebar.svelte
<script lang="ts" module>
  import { createFilter } from "@zag-js/i18n-utils"
  import { sidebarTree, type SidebarNode } from "@zag-js/shared"
  import * as tree from "@zag-js/tree-view"

  const baseCollection = tree.collection<SidebarNode>({
    nodeToValue: (node) => node.id,
    nodeToString: (node) => node.name,
    rootNode: sidebarTree,
  })

  const filter = createFilter({ sensitivity: "base" })

  // Mark a node as a keeper if it OR any ancestor matches; needed because `collection.filter`
  // alone would prune children of a matched branch when the children don't themselves match.
  function collectKeepSet(node: SidebarNode, query: string, ancestorMatched: boolean, keep: Set<string>): boolean {
    const selfMatched = ancestorMatched || filter.contains(node.name, query)
    let anyChildKept = false
    for (const child of node.children ?? []) {
      if (collectKeepSet(child, query, selfMatched, keep)) anyChildKept = true
    }
    if (selfMatched || anyChildKept) {
      keep.add(node.id)
      return true
    }
    return false
  }

  function getActiveValueFromPath(pathname: string): string | null {
    const segments = pathname.split("/").filter(Boolean)
    if (segments.length < 2) return null
    return `${segments[0]}/${segments[1]}`
  }

  function buildSearch(selected: string | null, expanded: string[]): string {
    const params = new URLSearchParams()
    if (selected) params.set("selected", selected)
    if (expanded.length) params.set("expanded", expanded.join(","))
    const out = params.toString()
    return out ? `?${out}` : ""
  }
</script>

<script lang="ts">
  import { page } from "$app/stores"
  import { normalizeProps, useMachine } from "@zag-js/svelte"
  import { ChevronRightIcon, SearchIcon, XIcon } from "lucide-svelte"
  import styles from "@styles/sidebar.module.css"

  let query = $state("")
  let localExpanded = $state<string[] | null>(null)
  let searchExpanded = $state<string[] | null>(null)

  const selectedFromParam = $derived($page.url.searchParams.get("selected"))
  const selectedFromPath = $derived(getActiveValueFromPath($page.url.pathname))
  const activeValue = $derived(selectedFromParam || selectedFromPath)
  const activeBranch = $derived(activeValue?.split("/")[0])

  const expandedRaw = $derived($page.url.searchParams.get("expanded"))
  const expandedFromUrl = $derived.by<string[]>(() => {
    if (expandedRaw == null) return activeBranch ? [activeBranch] : []
    return expandedRaw ? expandedRaw.split(",").filter(Boolean) : []
  })

  const expandedKey = $derived(expandedFromUrl.join("|"))
  $effect(() => {
    expandedKey
    localExpanded = null
  })

  const expandedValue = $derived(localExpanded ?? expandedFromUrl)

  const collection = $derived.by(() => {
    const trimmed = query.trim()
    if (!trimmed) return baseCollection
    const keep = new Set<string>()
    sidebarTree.children?.forEach((child) => collectKeepSet(child, trimmed, false, keep))
    return baseCollection.filter((node) => keep.has(node.id))
  })

  // Search expansion is local-only — searching shouldn't pollute the URL.
  $effect(() => {
    if (!query.trim()) {
      searchExpanded = null
      return
    }
    searchExpanded = collection.getBranchValues()
  })

  const machineExpanded = $derived(searchExpanded ?? expandedValue)

  const id = $props.id()
  const service = useMachine(tree.machine, () => ({
    id,
    collection,
    selectedValue: activeValue ? [activeValue] : [],
    expandedValue: machineExpanded,
    onExpandedChange: (details) => {
      if (query.trim()) {
        searchExpanded = details.expandedValue
        return
      }
      localExpanded = details.expandedValue
    },
  }))

  const api = $derived(tree.connect(service, normalizeProps))
</script>

{#snippet treeNode(node: SidebarNode, indexPath: number[])}
  {@const nodeProps = { indexPath, node }}
  {@const nodeState = api.getNodeState(nodeProps)}
  {@const target = node.href ? node : node.children?.find((c) => c.href)}
  {@const nextExpanded =
    nodeState.isBranch && !machineExpanded.includes(node.id) ? [...machineExpanded, node.id] : machineExpanded}
  {@const href = target?.href ? `${target.href}${buildSearch(target.id, nextExpanded)}` : "#"}

  <div {...api.getNodeGroupProps(nodeProps)}>
    <a {href} {...api.getNodeProps(nodeProps)}>
      <div {...api.getCellProps(nodeProps)}>
        {#if nodeState.isBranch}
          <span {...api.getNodeIndicatorProps({ ...nodeProps, type: "expanded" })} class={styles.chevron}>
            <ChevronRightIcon size={14} />
          </span>
        {/if}
        <span {...api.getNodeTextProps(nodeProps)} class={styles.label}>
          {node.name}
        </span>
      </div>
    </a>
    {#if nodeState.isBranch}
      <div {...api.getNodeGroupContentProps(nodeProps)}>
        {#each node.children || [] as child, index}
          {@render treeNode(child, [...indexPath, index])}
        {/each}
      </div>
    {/if}
  </div>
{/snippet}

<aside class={styles.sidebar}>
  <header class={styles.header}>
    <strong>Zagjs</strong>
  </header>

  <div class={styles.search}>
    <SearchIcon size={14} aria-hidden="true" />
    <input type="search" placeholder="Find component" bind:value={query} />
    {#if query}
      <button type="button" class={styles.clear} aria-label="Clear search" onclick={() => (query = "")}>
        <XIcon size={14} />
      </button>
    {/if}
  </div>

  <div {...api.getRootProps()} class={styles.tree}>
    <div {...api.getTreeProps()}>
      {#if collection.rootNode.children?.length}
        {#each collection.rootNode.children as node, index}
          {@render treeNode(node, [index])}
        {/each}
      {:else}
        <p class={styles.empty}>No matches</p>
      {/if}
    </div>
  </div>
</aside>
