// examples/nuxt-ts/app/components/Toolbar.vue
<script setup lang="ts">
import { dataAttr } from "@zag-js/dom-query"

const props = defineProps<{
  viz?: boolean
}>()

const slots = useSlots()

const controls = !!slots.controls
const activeState = ref(props.viz ? 1 : !controls ? 1 : 0)
</script>

<template>
  <div class="toolbar">
    <nav>
      <button v-if="controls" :data-active="dataAttr(activeState === 0)" @click="() => (activeState = 0)">
        Controls
      </button>

      <button :data-active="dataAttr(activeState === 1)" @click="() => (activeState = 1)">Visualizer</button>
    </nav>
    <div>
      <div v-if="controls" data-content :data-active="dataAttr(activeState === 0)">
        <slot name="controls" />
      </div>

      <div data-content :data-active="dataAttr(activeState === 1)">
        <slot />
      </div>
    </div>
  </div>
</template>

// examples/svelte-ts/src/lib/components/toolbar.svelte
<script lang="ts">
  import type { UseControlsReturn } from "$lib/use-controls.svelte"
  import { dataAttr } from "@zag-js/dom-query"
  import Controls from "./controls.svelte"

  interface Props {
    controls?: UseControlsReturn | null
    viz?: boolean
  }

  const { controls, viz }: Props = $props()

  let active = $state(viz ? 1 : !controls ? 1 : 0)
</script>

<div class="toolbar">
  <nav>
    {#if controls}
      <button data-active={dataAttr(active === 0)} onclick={() => (active = 0)}>Controls</button>
    {/if}
    <button data-active={dataAttr(active === 1)} onclick={() => (active = 1)}>Visualizer</button>
  </nav>
  {#if controls}
    <div data-content data-active={dataAttr(active === 0)}>
      <Controls {controls} />
    </div>
  {/if}
  <div data-content data-active={dataAttr(active === 1)}>
    <slot />
  </div>
</div>
