// examples/nuxt-ts/app/pages/image-cropper/circle.vue
<script setup lang="ts">
import styles from "../../../../../shared/src/css/image-cropper.module.css"
import * as imageCropper from "@zag-js/image-cropper"
import { imageCropperControls, handlePositions } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/vue"

const controls = useControls(imageCropperControls)

const zoom = ref(1)
const rotation = ref(0)

const service = useMachine(
  imageCropper.machine,
  computed(() => ({
    ...controls.context.value,
    id: useId(),
    cropShape: "circle" as const,
    zoom: zoom.value,
    onZoomChange(details) {
      zoom.value = details.zoom
    },
    rotation: rotation.value,
    onRotationChange(details) {
      rotation.value = details.rotation
    },
  })),
)

const api = computed(() => imageCropper.connect(service, normalizeProps))
</script>

<template>
  <main class="image-cropper">
    <div v-bind="api.getRootProps()">
      <div v-bind="api.getViewportProps()">
        <img src="https://picsum.photos/seed/a/500/300" v-bind="api.getImageProps()" :class="styles.Image" />
        <div v-bind="api.getSelectionProps()" :class="styles.Selection">
          <div v-for="position in handlePositions" :key="position" v-bind="api.getHandleProps({ position })" :class="styles.Handle">
            <div />
          </div>
        </div>
      </div>
    </div>
    <label>
      Zoom:
      <input
        type="range"
        :min="service.prop('minZoom')"
        :max="service.prop('maxZoom')"
        :step="service.prop('zoomStep')"
        :value="zoom"
        data-testid="zoom-slider"
        @input="(e) => api.setZoom(Number((e.target as HTMLInputElement).value))"
      />
    </label>
    <label>
      Rotation:
      <input
        type="range"
        :min="0"
        :max="360"
        :step="1"
        :value="rotation"
        data-testid="rotation-slider"
        @input="(e) => api.setRotation(Number((e.target as HTMLInputElement).value))"
      />
    </label>
  </main>

  <Toolbar>
    <StateVisualizer :state="service" :context="['naturalSize', 'crop', 'zoom', 'rotation', 'offset']" />
    <template #controls>
      <Controls :control="controls" />
    </template>
  </Toolbar>
</template>

// examples/next-ts/pages/image-cropper/circle.tsx
import styles from "../../../../shared/src/css/image-cropper.module.css"
import * as imageCropper from "@zag-js/image-cropper"
import { useMachine, normalizeProps } from "@zag-js/react"
import { imageCropperControls } from "@zag-js/shared"
import { useId, useState } from "react"
import { StateVisualizer } from "../../components/state-visualizer"
import { Toolbar } from "../../components/toolbar"
import { handlePositions } from "@zag-js/shared"
import { useControls } from "../../hooks/use-controls"

export default function Page() {
  const controls = useControls(imageCropperControls)
  const [zoom, setZoom] = useState(1)
  const [rotation, setRotation] = useState(0)

  const service = useMachine(imageCropper.machine, {
    id: useId(),
    zoom,
    onZoomChange(details) {
      setZoom(details.zoom)
    },
    rotation,
    onRotationChange(details) {
      setRotation(details.rotation)
    },
    cropShape: "circle",
    ...controls.context,
  })

  const api = imageCropper.connect(service, normalizeProps)

  return (
    <>
      <main className="image-cropper">
        <div {...api.getRootProps()}>
          <div {...api.getViewportProps()}>
            <img src="https://picsum.photos/seed/a/500/300" {...api.getImageProps()} className={styles.Image} />
            <div {...api.getSelectionProps()} className={styles.Selection}>
              {handlePositions.map((position) => (
                <div key={position} {...api.getHandleProps({ position })} className={styles.Handle}>
                  <div />
                </div>
              ))}
            </div>
          </div>
        </div>
        <label>
          Zoom:
          <input
            type="range"
            min={service.prop("minZoom")}
            max={service.prop("maxZoom")}
            step={service.prop("zoomStep")}
            value={zoom}
            data-testid="zoom-slider"
            onChange={(e) => api.setZoom(Number(e.currentTarget.value))}
          />
        </label>
        <label>
          Rotation:
          <input
            type="range"
            min={0}
            max={360}
            step={1}
            value={rotation}
            data-testid="rotation-slider"
            onChange={(e) => api.setRotation(Number(e.currentTarget.value))}
          />
        </label>
      </main>

      <Toolbar controls={controls.ui}>
        <StateVisualizer state={service} context={["naturalSize", "crop", "zoom", "rotation", "offset"]} />
      </Toolbar>
    </>
  )
}
