// examples/nuxt-ts/app/pages/menu/default-open.vue
<script setup lang="ts">
import * as menu from "@zag-js/menu"
import { menuControls } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/vue"
import "@styles/menu.css"

const controls = useControls(menuControls)

const service = useMachine(
  menu.machine,
  controls.mergeProps<menu.Props>({
    id: useId(),
    defaultOpen: true,
    onSelect: console.log,
  }),
)

const api = computed(() => menu.connect(service, normalizeProps))
</script>

<template>
  <main>
    <div>
      <button v-bind="api.getTriggerProps()">Actions <span v-bind="api.getIndicatorProps()">▾</span></button>
      <Teleport to="#teleports">
        <div v-bind="api.getPositionerProps()">
          <ul v-bind="api.getContentProps()">
            <li v-bind="api.getItemProps({ value: 'edit' })">Edit</li>
            <li v-bind="api.getItemProps({ value: 'duplicate' })">Duplicate</li>
            <li v-bind="api.getItemProps({ value: 'delete' })">Delete</li>
            <li v-bind="api.getItemProps({ value: 'export' })">Export...</li>
          </ul>
        </div>
      </Teleport>
    </div>
  </main>

  <Toolbar>
    <StateVisualizer :state="service" />
    <template #controls>
      <Controls :control="controls" />
    </template>
  </Toolbar>
</template>

// examples/svelte-ts/src/routes/menu/default-open/+page.svelte
<script lang="ts">
  import StateVisualizer from "$lib/components/state-visualizer.svelte"
  import Toolbar from "$lib/components/toolbar.svelte"
  import { useControls } from "$lib/use-controls.svelte"
  import * as menu from "@zag-js/menu"
  import { menuControls } from "@zag-js/shared"
  import { normalizeProps, portal, useMachine } from "@zag-js/svelte"
  import "@styles/menu.css"

  const controls = useControls(menuControls)

  const id = $props.id()
  const service = useMachine(
    menu.machine,
    controls.mergeProps<menu.Props>({
      id,
      defaultOpen: true,
      onSelect: console.log,
    }),
  )

  const api = $derived(menu.connect(service, normalizeProps))
</script>

<main>
  <div>
    <button {...api.getTriggerProps()}>
      Actions <span {...api.getIndicatorProps()}>▾</span>
    </button>
    <div use:portal {...api.getPositionerProps()}>
      <ul {...api.getContentProps()}>
        <li {...api.getItemProps({ value: "edit" })}>Edit</li>
        <li {...api.getItemProps({ value: "duplicate" })}>Duplicate</li>
        <li {...api.getItemProps({ value: "delete" })}>Delete</li>
        <li {...api.getItemProps({ value: "export" })}>Export...</li>
      </ul>
    </div>
  </div>
</main>

<Toolbar {controls}>
  <StateVisualizer state={service} />
</Toolbar>
