// examples/solid-ts/src/routes/drawer/basic.tsx
import * as drawer from "@zag-js/drawer"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { createMemo, createUniqueId, For } from "solid-js"
import { drawerControls } from "@zag-js/shared"
import { StateVisualizer } from "../../components/state-visualizer"
import { Toolbar } from "../../components/toolbar"
import { useControls } from "../../hooks/use-controls"
import styles from "../../../../shared/styles/drawer.module.css"

export default function Page() {
  const controls = useControls(drawerControls)

  const service = useMachine(
    drawer.machine,
    controls.mergeProps({
      id: createUniqueId(),
    }),
  )

  const api = createMemo(() => drawer.connect(service, normalizeProps))

  return (
    <>
      <main>
        <button class={styles.trigger} {...api().getTriggerProps()}>
          Open
        </button>
        <div class={styles.backdrop} {...api().getBackdropProps()} />
        <div class={styles.positioner} {...api().getPositionerProps()}>
          <div class={styles.content} {...api().getContentProps()}>
            <div class={styles.grabber} {...api().getGrabberProps()}>
              <div class={styles.grabberIndicator} {...api().getGrabberIndicatorProps()} />
            </div>
            <div {...api().getTitleProps()}>Drawer</div>
            <div data-no-drag="true" class={styles.noDrag}>
              No drag area
            </div>
            <div class={styles.scrollable}>
              <For each={Array.from({ length: 100 })}>{(_element, index) => <div>Item {index()}</div>}</For>
            </div>
          </div>
        </div>
      </main>

      <Toolbar controls={controls}>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}

// examples/svelte-ts/src/routes/hover-card/basic/+page.svelte
<script lang="ts">
  import styles from "../../../../../../shared/src/css/hover-card.module.css"
  import StateVisualizer from "$lib/components/state-visualizer.svelte"
  import Toolbar from "$lib/components/toolbar.svelte"
  import { useControls } from "$lib/use-controls.svelte"
  import * as hoverCard from "@zag-js/hover-card"
  import { hoverCardControls } from "@zag-js/shared"
  import { normalizeProps, portal, useMachine } from "@zag-js/svelte"

  const controls = useControls(hoverCardControls)

  const id = $props.id()
  const service = useMachine(hoverCard.machine, controls.mergeProps<hoverCard.Props>({ id }))

  const api = $derived(hoverCard.connect(service, normalizeProps))
</script>

<main class="hover-card">
  <div style="display:flex; gap:50px">
    <a href="https://twitter.com/zag_js" target="_blank" {...api.getTriggerProps()} class={styles.Trigger}> Twitter </a>

    {#if api.open}
      <div use:portal {...api.getPositionerProps()}>
        <div {...api.getContentProps()} class={styles.Content}>
          <div {...api.getArrowProps()}>
            <div {...api.getArrowTipProps()}></div>
          </div>
          Twitter Preview
          <a href="https://twitter.com/zag_js" target="_blank"> Twitter </a>
        </div>
      </div>
    {/if}

    <div data-part="test-text">Test text</div>
  </div>
</main>

<Toolbar {controls}>
  <StateVisualizer state={service} />
</Toolbar>
