// examples/solid-ts/src/routes/menu/default-open.tsx
import * as menu from "@zag-js/menu"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { createMemo, createUniqueId } from "solid-js"
import { Portal } from "solid-js/web"
import { menuControls } from "@zag-js/shared"
import { StateVisualizer } from "~/components/state-visualizer"
import { Toolbar } from "~/components/toolbar"
import { useControls } from "~/hooks/use-controls"
import "@styles/menu.css"

export default function Page() {
  const controls = useControls(menuControls)
  const service = useMachine(menu.machine, { id: createUniqueId(), defaultOpen: true })

  const api = createMemo(() => menu.connect(service, normalizeProps))

  return (
    <>
      <main>
        <div>
          <button {...api().getTriggerProps()}>
            Actions <span {...api().getIndicatorProps()}>▾</span>
          </button>

          <Portal>
            <div {...api().getPositionerProps()}>
              <ul {...api().getContentProps()}>
                <li {...api().getItemProps({ value: "edit" })}>Edit</li>
                <li {...api().getItemProps({ value: "duplicate" })}>Duplicate</li>
                <li {...api().getItemProps({ value: "delete" })}>Delete</li>
                <li {...api().getItemProps({ value: "export" })}>Export...</li>
              </ul>
            </div>
          </Portal>
        </div>
      </main>

      <Toolbar controls={controls}>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}

// examples/next-ts/app/menu/default-open/page.tsx
"use client"

import * as menu from "@zag-js/menu"
import { normalizeProps, Portal, useMachine } from "@zag-js/react"
import { menuControls } from "@zag-js/shared"
import { useId } from "react"
import { StateVisualizer } from "@/components/state-visualizer"
import { Toolbar } from "@/components/toolbar"
import { useControls } from "@/hooks/use-controls"
import "@styles/menu.css"

export default function Page() {
  const controls = useControls(menuControls)
  const service = useMachine(menu.machine, {
    id: useId(),
    defaultOpen: true,
    onSelect: console.log,
    ...controls.context,
  })

  const api = menu.connect(service, normalizeProps)

  return (
    <>
      <main>
        <div>
          <button {...api.getTriggerProps()}>
            Actions <span {...api.getIndicatorProps()}>▾</span>
          </button>
          {api.open && (
            <Portal>
              <div {...api.getPositionerProps()}>
                <ul {...api.getContentProps()}>
                  <li {...api.getItemProps({ value: "edit" })}>Edit</li>
                  <li {...api.getItemProps({ value: "duplicate" })}>Duplicate</li>
                  <li {...api.getItemProps({ value: "delete" })}>Delete</li>
                  <li {...api.getItemProps({ value: "export" })}>Export...</li>
                </ul>
              </div>
            </Portal>
          )}
        </div>
      </main>
      <Toolbar controls={controls.ui}>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}
