// examples/solid-ts/src/routes/virtualizer/window.tsx
import { Index } from "solid-js"
import { useWindowVirtualizer } from "../../hooks/use-virtualizer"

const ITEM_COUNT = 10_000

const items = Array.from({ length: ITEM_COUNT }, (_, index) => ({
  id: `item-${index}`,
  name: `Item ${index + 1}`,
}))

export default function Page() {
  const { virtualizer, ref } = useWindowVirtualizer({
    count: ITEM_COUNT,
    estimatedSize: () => 72,
    overscan: 8,
  })

  return (
    <main style={{ padding: "20px", width: "100%", "max-width": "960px" }}>
      <h1>Window Virtualizer</h1>
      <p style={{ color: "#64748b" }}>Uses the page scroll container instead of an explicit scrolling element.</p>

      <div
        ref={ref}
        {...virtualizer.getContainerAriaAttrs()}
        style={{
          ...virtualizer.getContainerStyle(),
          width: "100%",
          border: "1px solid #d1d5db",
          "border-radius": "8px",
          "margin-top": "16px",
        }}
      >
        <div style={{ height: `${virtualizer.getTotalSize()}px`, width: "100%", position: "relative" }}>
          <Index each={virtualizer.getVirtualItems()}>
            {(virtualItem) => (
              <div
                data-index={virtualItem().index}
                style={{
                  ...virtualizer.getItemStyle(virtualItem()),
                  padding: "12px 16px",
                  "border-bottom": "1px solid #e5e7eb",
                  background: virtualItem().index % 2 === 0 ? "#f8fafc" : "#fff",
                }}
              >
                {items[virtualItem().index]?.name}
              </div>
            )}
          </Index>
        </div>
      </div>
    </main>
  )
}

// examples/svelte-ts/src/routes/virtualizer/window/+page.svelte
<script lang="ts">
  import { useWindowVirtualizer } from "$lib/use-virtualizer.svelte"

  const ITEM_COUNT = 10_000
  const items = Array.from({ length: ITEM_COUNT }, (_, index) => ({
    id: `item-${index}`,
    name: `Item ${index + 1}`,
  }))

  let rootEl = $state<HTMLDivElement | null>(null)

  const { virtualizer, init } = useWindowVirtualizer({
    count: ITEM_COUNT,
    estimatedSize: () => 72,
    overscan: 8,
    initialRect:
      typeof window !== "undefined"
        ? { width: window.innerWidth, height: window.innerHeight }
        : { width: 0, height: 800 },
  })

  $effect(() => {
    init(rootEl)
  })
</script>

<main style="padding: 20px; width: 100%; max-width: 960px">
  <h1>Window Virtualizer</h1>
  <p style="color: #64748b">Uses the page scroll container instead of an explicit scrolling element.</p>

  <div
    bind:this={rootEl}
    {...virtualizer.getContainerAriaAttrs()}
    style="width: 100%; border: 1px solid #d1d5db; border-radius: 8px; margin-top: 16px; position: relative;"
  >
    <div style={`height: ${virtualizer.getTotalSize()}px; width: 100%; position: relative`}>
      {#each virtualizer.getVirtualItems() as virtualItem (items[virtualItem.index]?.id)}
        <div
          style={`position: absolute; left: 0; width: 100%; transform: translateY(${virtualItem.start}px); height: ${virtualItem.size}px; padding: 12px 16px; border-bottom: 1px solid #e5e7eb; background: ${virtualItem.index % 2 === 0 ? "#f8fafc" : "#fff"}; box-sizing: border-box;`}
        >
          {items[virtualItem.index]?.name}
        </div>
      {/each}
    </div>
  </div>
</main>
