// packages/core/react/src/use-machine.ts
import { MachineSrc, StateMachine as S } from "@ui-machines/core"
import { useEffect, useLayoutEffect } from "react"
import { useSnapshot } from "valtio"
import { useConstant } from "./use-constant"

const useSafeLayoutEffect = typeof document !== "undefined" ? useLayoutEffect : useEffect

export function useMachine<
  TContext extends Record<string, any>,
  TState extends S.StateSchema,
  TEvent extends S.EventObject = S.AnyEventObject,
>(
  machine: MachineSrc<TContext, TState, TEvent>,
  options?: S.MachineOptions<TContext, TState, TEvent> & {
    state?: S.StateInit<TContext, TState>
  },
) {
  const { actions, state: hydratedState } = options ?? {}
  const service = useConstant(() => {
    const resolvedMachine = typeof machine === "function" ? machine() : machine.clone()
    return options ? resolvedMachine.withOptions(options) : resolvedMachine
  })

  useSafeLayoutEffect(() => {
    service.start(hydratedState)
    return () => void service.stop()
  }, [service])

  useSafeLayoutEffect(() => {
    service.updateActions(actions)
  }, [actions])

  const state = useSnapshot(service.state)
  const _state = <S.State<TContext, TState>>state

  return [_state, service.send, service] as const
}

// packages/core/solid/src/use-machine.ts
import { MachineSrc, StateMachine as S } from "@ui-machines/core"
import { createSignal, onCleanup, onMount } from "solid-js"

export function useMachine<
  TContext extends Record<string, any>,
  TState extends S.StateSchema,
  TEvent extends S.EventObject = S.AnyEventObject,
>(
  machine: MachineSrc<TContext, TState, TEvent>,
  options?: S.MachineOptions<TContext, TState, TEvent> & {
    state?: S.StateInit<TContext, TState>
  },
) {
  const { actions, state: hydratedState } = options ?? {}

  const service = (() => {
    const resolvedMachine = typeof machine === "function" ? machine() : machine.clone()
    return options ? resolvedMachine.withOptions(options) : resolvedMachine
  })()

  const [state, setState] = createSignal({} as S.State<TContext, TState>)

  let unsubscribe: () => void

  onMount(() => {
    service.start(hydratedState)
    unsubscribe = service.subscribe(setState)
  })

  onCleanup(() => {
    service.stop()
    unsubscribe()
  })

  onMount(() => {
    service.updateActions(actions)
  })

  return [state, service.send, service] as const
}
