// examples/preact-ts/src/pages/toc/basic.tsx
import { normalizeProps, useMachine } from "@zag-js/preact"
import { tocControls, tocData } from "@zag-js/shared"
import * as toc from "@zag-js/toc"
import { useId } from "react"
import { StateVisualizer } from "../../components/state-visualizer"
import { Toolbar } from "../../components/toolbar"
import { useControls } from "../../hooks/use-controls"

export default function Page() {
  const controls = useControls(tocControls)

  const service = useMachine(toc.machine, {
    id: useId(),
    items: tocData,
    ...controls.context,
  })

  const api = toc.connect(service, normalizeProps)

  return (
    <>
      <main className="toc">
        <div style={{ display: "flex", gap: "2rem" }}>
          <nav {...api.getRootProps()}>
            <h5 {...api.getTitleProps()}>On this page</h5>
            <ul {...api.getListProps()}>
              {tocData.map((item) => (
                <li key={item.value} {...api.getItemProps({ item })}>
                  <a href={`#${item.value}`} {...api.getLinkProps({ item })}>
                    {item.label}
                  </a>
                </li>
              ))}
            </ul>
          </nav>

          <div style={{ maxHeight: "20rem", overflow: "auto", flex: 1 }}>
            {tocData.map((item) => (
              <div key={item.value} style={{ marginBottom: "1rem" }}>
                <h2 id={item.value} style={{ fontSize: item.depth === 2 ? "1.25rem" : "1rem" }}>
                  {item.label}
                </h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
                  dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.
                </p>
              </div>
            ))}
          </div>
        </div>
      </main>

      <Toolbar controls={controls.ui}>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}

// examples/svelte-ts/src/routes/toc/basic/+page.svelte
<script lang="ts">
  import * as toc from "@zag-js/toc"
  import { tocControls, tocData } from "@zag-js/shared"
  import { normalizeProps, useMachine } from "@zag-js/svelte"
  import Toolbar from "$lib/components/toolbar.svelte"
  import StateVisualizer from "$lib/components/state-visualizer.svelte"
  import { useControls } from "$lib/use-controls.svelte"

  const controls = useControls(tocControls)

  const id = $props.id()
  const service = useMachine(
    toc.machine,
    controls.mergeProps<toc.Props>({
      id,
      items: tocData,
    }),
  )

  const api = $derived(toc.connect(service, normalizeProps))
</script>

<main class="toc">
  <div style="display: flex; gap: 2rem;">
    <nav {...api.getRootProps()}>
      <h5 {...api.getTitleProps()}>On this page</h5>
      <ul {...api.getListProps()}>
        {#each tocData as item}
          <li {...api.getItemProps({ item })}>
            <a href={`#${item.value}`} {...api.getLinkProps({ item })}>
              {item.label}
            </a>
          </li>
        {/each}
      </ul>
    </nav>

    <div style="max-height: 20rem; overflow: auto; flex: 1;">
      {#each tocData as item}
        <div style="margin-bottom: 1rem;">
          <h2 id={item.value} style="font-size: {item.depth === 2 ? '1.25rem' : '1rem'}">
            {item.label}
          </h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.
          </p>
        </div>
      {/each}
    </div>
  </div>
</main>

<Toolbar {controls}>
  <StateVisualizer state={service} />
</Toolbar>
