// examples/solid-ts/src/routes/select/default-open.tsx
import * as select from "@zag-js/select"
import { selectControls, selectData } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/solid"
import serialize from "form-serialize"
import { Index, createMemo, createUniqueId } from "solid-js"
import { Portal } from "solid-js/web"
import { StateVisualizer } from "~/components/state-visualizer"
import { Toolbar } from "~/components/toolbar"
import { useControls } from "~/hooks/use-controls"
import "@styles/select.css"

export default function Page() {
  const controls = useControls(selectControls)

  const service = useMachine(
    select.machine,
    controls.mergeProps<select.Props>(() => ({
      collection: select.collection({ items: selectData }),
      id: createUniqueId(),
      defaultOpen: true,
    })),
  )

  const api = createMemo(() => select.connect(service, normalizeProps))

  return (
    <>
      <main class="select">
        <div {...api().getRootProps()}>
          {/* control */}
          <div {...api().getControlProps()}>
            <label {...api().getLabelProps()}>Label</label>
            <button {...api().getTriggerProps()}>
              {api().valueAsString || "Select option"}
              <span {...api().getIndicatorProps()}>▼</span>
            </button>
          </div>

          <form
            onInput={(e) => {
              const form = e.currentTarget as HTMLFormElement
              const formData = serialize(form, { hash: true })
              console.log(formData)
            }}
          >
            {/* Hidden select */}
            <select {...api().getHiddenSelectProps()}>
              <Index each={selectData}>{(option) => <option value={option().value}>{option().label}</option>}</Index>
            </select>
          </form>

          {/* UI select */}
          <Portal>
            <div {...api().getPositionerProps()}>
              <div {...api().getContentProps()}>
                <div {...api().getListProps()}>
                  <Index each={selectData}>
                    {(item) => (
                      <div {...api().getItemProps({ item: item() })}>
                        <span {...api().getItemTextProps({ item: item() })}>{item().label}</span>
                        <span {...api().getItemIndicatorProps({ item: item() })}>✓</span>
                      </div>
                    )}
                  </Index>
                </div>
              </div>
            </div>
          </Portal>
        </div>
      </main>

      <Toolbar controls={controls}>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}

// examples/nuxt-ts/app/pages/select/default-open.vue
<script setup lang="tsx">
import * as select from "@zag-js/select"
import { selectControls, selectData } from "@zag-js/shared"
import serialize from "form-serialize"
import { normalizeProps, useMachine } from "@zag-js/vue"
import "@styles/select.css"

const controls = useControls(selectControls)

const service = useMachine(
  select.machine,
  controls.mergeProps<select.Props>({
    collection: select.collection({ items: selectData }),
    id: useId(),
    defaultOpen: true,
  }),
)

const api = computed(() => select.connect(service, normalizeProps))
</script>

<template>
  <main class="select">
    <div v-bind="api.getRootProps()">
      <div v-bind="api.getControlProps()">
        <label v-bind="api.getLabelProps()">Label</label>
        <button v-bind="api.getTriggerProps()">
          <span>{{ api.valueAsString || "Select option" }}</span>
          <span v-bind="api.getIndicatorProps()">▼</span>
        </button>
      </div>
      <form
        @input="
          (e) => {
            const form = e.currentTarget as HTMLFormElement
            const formData = serialize(form, { hash: true })
            console.log(formData)
          }
        "
      >
        <select v-bind="api.getHiddenSelectProps()">
          <option v-for="option in selectData" :key="option.value" :value="option.value">{{ option.label }}</option>
        </select>
      </form>
      <Teleport to="#teleports">
        <div v-bind="api.getPositionerProps()">
          <div v-bind="api.getContentProps()">
            <div v-bind="api.getListProps()">
              <div v-for="item in selectData" :key="item.value" v-bind="api.getItemProps({ item })">
                <span v-bind="api.getItemTextProps({ item })">{{ item.label }}</span>
                <span v-bind="api.getItemIndicatorProps({ item })">✓</span>
              </div>
            </div>
          </div>
        </div>
      </Teleport>
    </div>
  </main>

  <Toolbar>
    <StateVisualizer :state="service" :omit="['collection']" />
    <template #controls>
      <Controls :control="controls" />
    </template>
  </Toolbar>
</template>
