// examples/nuxt-ts/app/pages/drawer/cross-axis-scroll.vue
<script setup lang="ts">
import * as drawer from "@zag-js/drawer"
import { normalizeProps, useMachine } from "@zag-js/vue"
import Presence from "~/components/Presence.vue"
import styles from "../../../../shared/styles/drawer.module.css"

const service = useMachine(drawer.machine, { id: useId() })

const api = computed(() => drawer.connect(service, normalizeProps))
</script>

<template>
  <main>
    <button v-bind="api.getTriggerProps()" :class="styles.trigger">Open Drawer</button>
    <Presence v-bind="api.getBackdropProps()" :class="styles.backdrop" />
    <div v-bind="api.getPositionerProps()" :class="styles.positioner">
      <Presence v-bind="api.getContentProps()" :class="styles.content">
        <div v-bind="api.getGrabberProps()" :class="styles.grabber">
          <div v-bind="api.getGrabberIndicatorProps()" :class="styles.grabberIndicator" />
        </div>
        <div v-bind="api.getTitleProps()">Cross-Axis Scroll</div>
        <p v-bind="api.getDescriptionProps()">
          Try scrolling the image carousel horizontally. It should scroll without triggering the drawer drag.
        </p>

        <div
          data-testid="horizontal-scroll"
          style="display: flex; gap: 12px; overflow-x: auto; padding: 16px"
        >
          <div
            v-for="i in 10"
            :key="i"
            style="
              width: 200px;
              height: 120px;
              border-radius: 12px;
              flex-shrink: 0;
              background: #e5e7eb;
              display: flex;
              align-items: center;
              justify-content: center;
              font-size: 24px;
              font-weight: bold;
              color: #6b7280;
            "
          >
            {{ i }}
          </div>
        </div>

        <div :class="styles.scrollable" data-testid="scrollable">
          <div v-for="(_element, index) in Array.from({ length: 50 })" :key="index" style="padding: 4px 16px">
            Item {{ index }}
          </div>
        </div>
      </Presence>
    </div>
  </main>

  <Toolbar>
    <StateVisualizer :state="service" :context="['dragOffset', 'snapPoint']" />
  </Toolbar>
</template>

// examples/next-ts/pages/drawer/cross-axis-scroll.tsx
import * as drawer from "@zag-js/drawer"
import { normalizeProps, useMachine } from "@zag-js/react"
import { useId } from "react"
import { Presence } from "../../components/presence"
import { StateVisualizer } from "../../components/state-visualizer"
import { Toolbar } from "../../components/toolbar"
import styles from "../../../shared/styles/drawer.module.css"

export default function Page() {
  const service = useMachine(drawer.machine, {
    id: useId(),
  })

  const api = drawer.connect(service, normalizeProps)

  return (
    <>
      <main>
        <button {...api.getTriggerProps()} className={styles.trigger}>
          Open Drawer
        </button>
        <Presence {...api.getBackdropProps()} className={styles.backdrop} />
        <div {...api.getPositionerProps()} className={styles.positioner}>
          <Presence {...api.getContentProps()} className={styles.content}>
            <div {...api.getGrabberProps()} className={styles.grabber}>
              <div {...api.getGrabberIndicatorProps()} className={styles.grabberIndicator} />
            </div>
            <div {...api.getTitleProps()}>Cross-Axis Scroll</div>
            <p {...api.getDescriptionProps()}>
              Try scrolling the image carousel horizontally. It should scroll without triggering the drawer drag.
            </p>

            {/* Horizontal scrollable content inside a vertical-swipe drawer */}
            <div
              data-testid="horizontal-scroll"
              style={{
                display: "flex",
                gap: "12px",
                overflowX: "auto",
                padding: "16px",
              }}
            >
              {Array.from({ length: 10 }, (_, i) => (
                <div
                  key={i}
                  style={{
                    width: "200px",
                    height: "120px",
                    borderRadius: "12px",
                    flexShrink: 0,
                    background: "#e5e7eb",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    fontSize: "24px",
                    fontWeight: "bold",
                    color: "#6b7280",
                  }}
                >
                  {i + 1}
                </div>
              ))}
            </div>

            {/* Vertical scrollable content */}
            <div className={styles.scrollable} data-testid="scrollable">
              {Array.from({ length: 50 }).map((_, index) => (
                <div key={index} style={{ padding: "4px 16px" }}>
                  Item {index}
                </div>
              ))}
            </div>
          </Presence>
        </div>
      </main>

      <Toolbar>
        <StateVisualizer state={service} context={["dragOffset", "snapPoint"]} />
      </Toolbar>
    </>
  )
}
