// packages/frameworks/lit/src/machine.ts
import type {
  ActionsOrFn,
  Bindable,
  BindableContext,
  BindableRefs,
  ChooseFn,
  ComputedFn,
  EffectsOrFn,
  GuardFn,
  Machine,
  MachineSchema,
  Params,
  PropFn,
  Scope,
  Service,
} from "@zag-js/core"
import { createScope, INIT_STATE, MachineStatus } from "@zag-js/core"
import { subscribe } from "@zag-js/store"
import { compact, identity, isEqual, isFunction, isString, runIfFn, toArray, warn } from "@zag-js/utils"
import type { ReactiveController, ReactiveControllerHost } from "lit"
import { bindable } from "./bindable"
import { createRefs } from "./refs"

export class LitMachine<T extends MachineSchema> {
  scope: Scope
  ctx: BindableContext<T>
  prop: PropFn<T>
  state: Bindable<T["state"]>
  refs: BindableRefs<T>
  computed: ComputedFn<T>

  private event: any = { type: "" }
  private previousEvent: any

  private effects = new Map<string, VoidFunction>()
  private transition: any = null

  private cleanups: VoidFunction[] = []
  private subscriptions: Array<(service: Service<T>) => void> = []

  private getEvent = () => ({
    ...this.event,
    current: () => this.event,
    previous: () => this.previousEvent,
  })

  private getState = () => ({
    ...this.state,
    matches: (...values: T["state"][]) => values.includes(this.state.get()),
    hasTag: (tag: T["tag"]) => !!this.machine.states[this.state.get() as T["state"]]?.tags?.includes(tag),
  })

  debug = (...args: any[]) => {
    if (this.machine.debug) console.log(...args)
  }

  notify = () => {
    this.publish()
  }

  constructor(
    private machine: Machine<T>,
    userProps: Partial<T["props"]> | (() => Partial<T["props"]>) = {},
  ) {
    // create scope
    const { id, ids, getRootNode } = runIfFn(userProps) as any
    this.scope = createScope({ id, ids, getRootNode })

    // create prop
    const prop: PropFn<T> = (key) => {
      const __props = runIfFn(userProps)
      const props: any = machine.props?.({ props: compact(__props), scope: this.scope }) ?? __props
      return props[key] as any
    }
    this.prop = prop

    // create context
    const context: any = machine.context?.({
      prop,
      bindable,
      scope: this.scope,
      flush(fn: VoidFunction) {
        queueMicrotask(fn)
      },
      getContext() {
        return ctx as any
      },
      getComputed() {
        return computed as any
      },
      getRefs() {
        return refs as any
      },
      getEvent: this.getEvent.bind(this),
    })

    // subscribe to context changes
    if (context) {
      Object.values(context).forEach((item: any) => {
        const unsub = subscribe(item.ref, () => this.notify())
        this.cleanups.push(unsub)
      })
    }

    // context function
    const ctx: BindableContext<T> = {
      get(key) {
        return context?.[key].get()
      },
      set(key, value) {
        context?.[key].set(value)
      },
      initial(key) {
        return context?.[key].initial
      },
      hash(key) {
        const current = context?.[key].get()
        return context?.[key].hash(current)
      },
    }
    this.ctx = ctx

    const computed: ComputedFn<T> = (key) => {
      return (
        machine.computed?.[key]({
          context: ctx as any,
          event: this.getEvent(),
          prop,
          refs: this.refs,
          scope: this.scope,
          computed: computed as any,
        }) ?? ({} as any)
      )
    }
    this.computed = computed

    const refs: BindableRefs<T> = createRefs(machine.refs?.({ prop, context: ctx }) ?? {})
    this.refs = refs

    // state
    const state = bindable(() => ({
      defaultValue: machine.initialState({ prop }),
      onChange: (nextState, prevState) => {
        // compute effects: exit -> transition -> enter

        // exit effects
        if (prevState) {
          const exitEffects = this.effects.get(prevState)
          exitEffects?.()
          this.effects.delete(prevState)
        }

        // exit actions
        if (prevState) {
          // @ts-ignore
          this.action(machine.states[prevState]?.exit)
        }

        // transition actions
        this.action(this.transition?.actions)

        // enter effect
        // @ts-ignore
        const cleanup = this.effect(machine.states[nextState]?.effects)
        if (cleanup) this.effects.set(nextState as string, cleanup)

        // root entry actions
        if (prevState === INIT_STATE) {
          this.action(machine.entry)
          const cleanup = this.effect(machine.effects)
          if (cleanup) this.effects.set(INIT_STATE, cleanup)
        }

        // enter actions
        // @ts-ignore
        this.action(machine.states[nextState]?.entry)
      },
    }))
    this.state = state
    this.cleanups.push(subscribe(this.state.ref, () => this.notify()))
  }

  send = (event: any) => {
    if (this.status !== MachineStatus.Started) return

    queueMicrotask(() => {
      this.previousEvent = this.event
      this.event = event

      this.debug("send", event)

      let currentState = this.state.get()

      const transitions =
        // @ts-ignore
        this.machine.states[currentState].on?.[event.type] ??
        // @ts-ignore
        this.machine.on?.[event.type]

      const transition = this.choose(transitions)
      if (!transition) return

      // save current transition
      this.transition = transition
      const target = transition.target ?? currentState

      this.debug("transition", transition)

      const changed = target !== currentState
      if (changed) {
        // state change is high priority
        this.state.set(target)
      } else {
        // call transition actions
        this.action(transition.actions)
      }
    })
  }

  private action = (keys: ActionsOrFn<T> | undefined) => {
    const strs = isFunction(keys) ? keys(this.getParams()) : keys
    if (!strs) return
    const fns = strs.map((s) => {
      const fn = this.machine.implementations?.actions?.[s]
      if (!fn) warn(`[zag-js] No implementation found for action "${JSON.stringify(s)}"`)
      return fn
    })
    for (const fn of fns) {
      fn?.(this.getParams())
    }
  }

  private guard = (str: T["guard"] | GuardFn<T>) => {
    if (isFunction(str)) return str(this.getParams())
    return this.machine.implementations?.guards?.[str](this.getParams())
  }

  private effect = (keys: EffectsOrFn<T> | undefined) => {
    const strs = isFunction(keys) ? keys(this.getParams()) : keys
    if (!strs) return
    const fns = strs.map((s) => {
      const fn = this.machine.implementations?.effects?.[s]
      if (!fn) warn(`[zag-js] No implementation found for effect "${JSON.stringify(s)}"`)
      return fn
    })
    const cleanups: VoidFunction[] = []
    for (const fn of fns) {
      const cleanup = fn?.(this.getParams())
      if (cleanup) cleanups.push(cleanup)
    }
    return () => cleanups.forEach((fn) => fn?.())
  }

  private choose: ChooseFn<T> = (transitions) => {
    return toArray(transitions).find((t: any) => {
      let result = !t.guard
      if (isString(t.guard)) result = !!this.guard(t.guard)
      else if (isFunction(t.guard)) result = t.guard(this.getParams())
      return result
    })
  }

  start() {
    this.status = MachineStatus.Started
    this.debug("initializing...")
    this.state.invoke(this.state.initial!, INIT_STATE)
    this.setupTrackers()
  }

  stop() {
    // run exit effects
    this.effects.forEach((fn) => fn?.())
    this.effects.clear()
    this.transition = null
    this.action(this.machine.exit)

    // unsubscribe from all subscriptions
    this.cleanups.forEach((unsub) => unsub())
    this.cleanups = []

    this.status = MachineStatus.Stopped
    this.debug("unmounting...")
  }

  subscribe = (fn: (service: Service<T>) => void) => {
    this.subscriptions.push(fn)
  }

  private status = MachineStatus.NotStarted

  get service(): Service<T> {
    return {
      state: this.getState(),
      send: this.send,
      context: this.ctx,
      prop: this.prop,
      scope: this.scope,
      refs: this.refs,
      computed: this.computed,
      event: this.getEvent(),
      getStatus: () => this.status,
    }
  }

  private publish = () => {
    this.callTrackers()
    this.subscriptions.forEach((fn) => fn(this.service))
  }

  private trackers: { deps: any[]; fn: any }[] = []

  private setupTrackers = () => {
    this.machine.watch?.(this.getParams())
  }

  private callTrackers = () => {
    this.trackers.forEach(({ deps, fn }) => {
      const next = deps.map((dep) => dep())
      if (!isEqual(fn.prev, next)) {
        fn()
        fn.prev = next
      }
    })
  }

  getParams = (): Params<T> => ({
    state: this.getState(),
    context: this.ctx,
    event: this.getEvent(),
    prop: this.prop,
    send: this.send,
    action: this.action,
    guard: this.guard,
    track: (deps: any[], fn: any) => {
      fn.prev = deps.map((dep) => dep())
      this.trackers.push({ deps, fn })
    },
    refs: this.refs,
    computed: this.computed,
    flush: identity,
    scope: this.scope,
    choose: this.choose,
  })
}

export class ZagController<T extends MachineSchema> implements ReactiveController {
  private machine: LitMachine<T>
  public api: any // Will be set in constructor and updated on changes

  constructor(
    private host: ReactiveControllerHost,
    machineConfig: Machine<T>,
    props: Partial<T["props"]> = {},
  ) {
    this.machine = new LitMachine(machineConfig, props)
    host.addController(this)
  }

  hostConnected() {
    this.machine.subscribe(() => {
      // Update API when machine state changes
      this.updateApi()
      // Request Lit component update
      this.host.requestUpdate()
    })
    this.machine.start()
    this.updateApi()
    // Trigger initial update to sync with host element
    this.host.requestUpdate()
  }

  hostDisconnected() {
    this.machine.stop()
  }

  private updateApi() {
    // This will be implemented once we have the connect function
    // For now, just expose the service
    this.api = this.machine.service
  }

  // Expose machine methods for advanced usage
  get service() {
    return this.machine.service
  }

  send = (event: any) => {
    this.machine.send(event)
  }
}

// packages/frameworks/solid/src/machine.ts
import type {
  ActionsOrFn,
  GuardFn,
  Machine,
  MachineSchema,
  Service,
  ChooseFn,
  ComputedFn,
  EffectsOrFn,
  BindableContext,
  Params,
} from "@zag-js/core"
import { createScope, INIT_STATE, MachineStatus } from "@zag-js/core"
import { compact, isFunction, isString, toArray, warn, ensure } from "@zag-js/utils"
import { type Accessor, createMemo, mergeProps, onCleanup, onMount } from "solid-js"
import { createBindable } from "./bindable"
import { createRefs } from "./refs"
import { createTrack } from "./track"

export function useMachine<T extends MachineSchema>(
  machine: Machine<T>,
  userProps: Partial<T["props"]> | Accessor<Partial<T["props"]>> = {},
): Service<T> {
  const scope = createMemo(() => {
    const { id, ids, getRootNode } = access(userProps) as any
    return createScope({ id, ids, getRootNode })
  })

  const debug = (...args: any[]) => {
    if (machine.debug) console.log(...args)
  }

  const props = createMemo(
    () =>
      machine.props?.({
        props: compact(access(userProps)),
        scope: scope(),
      }) ?? access(userProps),
  )

  const prop: any = createProp(props)

  const context: any = machine.context?.({
    prop,
    bindable: createBindable,
    get scope() {
      return scope()
    },
    flush,
    getContext() {
      return ctx as any
    },
    getComputed() {
      return computed as any
    },
    getRefs() {
      return refs as any
    },
    getEvent() {
      return getEvent()
    },
  })

  const ctx: BindableContext<T> = {
    get(key) {
      return context?.[key].get()
    },
    set(key, value) {
      context?.[key].set(value)
    },
    initial(key) {
      return context?.[key].initial
    },
    hash(key) {
      const current = context?.[key].get()
      return context?.[key].hash(current)
    },
  }

  const effects = { current: new Map<string, VoidFunction>() }
  const transitionRef: { current: any } = { current: null }

  const previousEventRef: { current: any } = { current: null }
  const eventRef: { current: any } = { current: { type: "" } }

  const getEvent = (): any =>
    mergeProps(eventRef.current, {
      current() {
        return eventRef.current
      },
      previous() {
        return previousEventRef.current
      },
    })

  const getState = () =>
    mergeProps(state, {
      matches(...values: T["state"][]) {
        const current = state.get()
        return values.includes(current)
      },
      hasTag(tag: T["tag"]) {
        const current = state.get()
        return !!machine.states[current as T["state"]]?.tags?.includes(tag)
      },
    })

  const refs = createRefs(machine.refs?.({ prop, context: ctx }) ?? {})

  const getParams = (): Params<T> => ({
    state: getState(),
    context: ctx,
    event: getEvent(),
    prop,
    send,
    action,
    guard,
    track: createTrack,
    refs,
    computed,
    flush,
    get scope() {
      return scope()
    },
    choose,
  })

  const action = (keys: ActionsOrFn<T> | undefined) => {
    const strs = isFunction(keys) ? keys(getParams()) : keys
    if (!strs) return
    const fns = strs.map((s) => {
      const fn = machine.implementations?.actions?.[s]
      if (!fn) warn(`[zag-js] No implementation found for action "${JSON.stringify(s)}"`)
      return fn
    })
    for (const fn of fns) {
      fn?.(getParams())
    }
  }

  const guard = (str: T["guard"] | GuardFn<T>) => {
    if (isFunction(str)) return str(getParams())
    return machine.implementations?.guards?.[str](getParams())
  }

  const effect = (keys: EffectsOrFn<T> | undefined) => {
    const strs = isFunction(keys) ? keys(getParams()) : keys
    if (!strs) return
    const fns = strs.map((s) => {
      const fn = machine.implementations?.effects?.[s]
      if (!fn) warn(`[zag-js] No implementation found for effect "${JSON.stringify(s)}"`)
      return fn
    })
    const cleanups: VoidFunction[] = []
    for (const fn of fns) {
      const cleanup = fn?.(getParams())
      if (cleanup) cleanups.push(cleanup)
    }
    return () => cleanups.forEach((fn) => fn?.())
  }

  const choose: ChooseFn<T> = (transitions) => {
    return toArray(transitions).find((t) => {
      let result = !t.guard
      if (isString(t.guard)) result = !!guard(t.guard)
      else if (isFunction(t.guard)) result = t.guard(getParams())
      return result
    })
  }

  const computed: ComputedFn<T> = (key) => {
    ensure(machine.computed, () => `[zag-js] No computed object found on machine`)
    const fn = machine.computed[key]
    return fn({
      context: ctx,
      event: eventRef.current,
      prop,
      refs,
      scope: scope(),
      computed: computed,
    })
  }

  const state = createBindable(() => ({
    defaultValue: machine.initialState({ prop }),
    onChange(nextState, prevState) {
      // compute effects: exit -> transition -> enter

      // exit effects
      if (prevState) {
        const exitEffects = effects.current.get(prevState)
        exitEffects?.()
        effects.current.delete(prevState)
      }

      // exit actions
      if (prevState) {
        action(machine.states[prevState]?.exit)
      }

      // transition actions
      action(transitionRef.current?.actions)

      // enter effect
      const cleanup = effect(machine.states[nextState]?.effects)
      if (cleanup) effects.current.set(nextState as string, cleanup)

      // root entry actions
      if (prevState === INIT_STATE) {
        action(machine.entry)
        const cleanup = effect(machine.effects)
        if (cleanup) effects.current.set(INIT_STATE, cleanup)
      }

      // enter actions
      action(machine.states[nextState]?.entry)
    },
  }))

  let status = MachineStatus.NotStarted

  onMount(() => {
    const started = status === MachineStatus.Started
    status = MachineStatus.Started
    debug(started ? "rehydrating..." : "initializing...")
    state.invoke(state.initial!, INIT_STATE)
  })

  onCleanup(() => {
    debug("unmounting...")
    status = MachineStatus.Stopped

    const fns = effects.current
    fns.forEach((fn) => fn?.())
    effects.current = new Map()
    transitionRef.current = null

    action(machine.exit)
  })

  const send = (event: any) => {
    if (status !== MachineStatus.Started) return

    previousEventRef.current = eventRef.current
    eventRef.current = event

    let currentState = state.get()

    const transitions =
      // @ts-ignore
      machine.states[currentState].on?.[event.type] ??
      // @ts-ignore
      machine.on?.[event.type]

    const transition = choose(transitions)
    if (!transition) return

    // save current transition
    transitionRef.current = transition
    const target = transition.target ?? currentState

    debug("transition", event.type, transition.target || currentState, `(${transition.actions})`)

    const changed = target !== currentState
    if (changed) {
      // state change is high priority
      state.set(target)
    } else if (transition.reenter && !changed) {
      // reenter will re-invoke the current state
      state.invoke(currentState, currentState)
    } else {
      // call transition actions
      action(transition.actions)
    }
  }

  machine.watch?.(getParams())

  return {
    state: getState(),
    send,
    context: ctx,
    prop,
    get scope() {
      return scope()
    },
    refs,
    computed,
    event: getEvent(),
    getStatus: () => status,
  } as unknown as Service<T>
}

function flush(fn: VoidFunction) {
  fn()
}

function access<T>(value: T | Accessor<T>) {
  return isFunction(value) ? value() : value
}

function createProp<T>(value: Accessor<T>) {
  return function get<K extends keyof T>(key: K): T[K] {
    return value()[key]
  }
}
