// packages/core/react/src/use-actor.ts
import { useEffect, useLayoutEffect, useRef, useState } from "react"
import { Machine, StateMachine as S } from "@ui-machines/core"
import { useConstant } from "./use-constant"

const useSafeLayoutEffect =
  typeof document !== "undefined" ? useLayoutEffect : useEffect

export function useActor<T extends Machine<any, any, any>>(service: T) {
  const ref = useRef(service)
  const [current, setCurrent] = useState(() => service.state)

  const send = useConstant(() => (event: S.Event<S.AnyEventObject>) => {
    ref.current.send(event)
  })

  useSafeLayoutEffect(() => {
    ref.current = service
    return service.subscribe((state) => {
      setCurrent(state)
    })
  }, [service])

  return [current as T["state"], send] as const
}

// packages/frameworks/solid/src/use-actor.ts
import { Machine, StateMachine as S } from "@ui-machines/core"
import { onCleanup } from "solid-js"
import { createStore } from "solid-js/store"
import { unwrap } from "./unwrap"

export function useActor<
  TContext extends Record<string, any>,
  TState extends S.StateSchema,
  TEvent extends S.EventObject = S.AnyEventObject,
>(service: Machine<TContext, TState, TEvent>) {
  const [current, setCurrent] = createStore<any>(unwrap(service.state))

  const unsubscribe = service.subscribe((state) => {
    setCurrent(state)
  })

  onCleanup(() => {
    unsubscribe()
  })

  return [current, service.send] as const
}
