// examples/svelte-ts/src/routes/meter/basic/+page.svelte
<script lang="ts">
  import StateVisualizer from "$lib/components/state-visualizer.svelte"
  import Toolbar from "$lib/components/toolbar.svelte"
  import { useControls } from "$lib/use-controls.svelte"
  import * as meter from "@zag-js/meter"
  import { meterControls } from "@zag-js/shared"
  import { normalizeProps, useMachine } from "@zag-js/svelte"
  import "@styles/meter.css"

  const controls = useControls(meterControls)

  const id = $props.id()
  const service = useMachine(
    meter.machine,
    controls.mergeProps<meter.Props>({
      id,
      defaultValue: 70,
      low: 60,
      high: 85,
      optimum: 10,
    }),
  )

  const api = $derived(meter.connect(service, normalizeProps))

  const presets = [
    { value: 10, label: "10%" },
    { value: 70, label: "70%" },
    { value: 95, label: "95%" },
  ]
</script>

<main class="meter">
  <div {...api.getRootProps()}>
    <div style="display: flex; justify-content: space-between; align-items: baseline">
      <span {...api.getLabelProps()}>Storage used</span>
      <span {...api.getValueTextProps()}>{api.valueAsString} · {api.valueState}</span>
    </div>
    <div {...api.getTrackProps()}>
      <div {...api.getIndicatorProps()}></div>
    </div>
  </div>

  <p>
    Optimum is below <code>low</code>, so a smaller value is better. 10 is optimal, 70 is suboptimal, 95 is
    least-optimal.
  </p>

  <div class="meter-actions">
    {#each presets as { value, label } (value)}
      <button data-testid="set-{value}" type="button" onclick={() => api.setValue(value)}>Set {label}</button>
    {/each}
  </div>
</main>

<Toolbar {controls}>
  <StateVisualizer state={service} />
</Toolbar>

// examples/nuxt-ts/app/pages/progress/basic.vue
<script setup lang="ts">
import * as progress from "@zag-js/progress"
import { progressControls } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/vue"
import "@styles/progress.css"

const controls = useControls(progressControls)

const service = useMachine(
  progress.machine,
  controls.mergeProps<progress.Props>({
    id: useId(),
  }),
)

const api = computed(() => progress.connect(service, normalizeProps))
</script>

<template>
  <main class="progress">
    <div v-bind="api.getRootProps()">
      <div v-bind="api.getLabelProps()">Upload progress</div>
      <svg v-bind="api.getCircleProps()">
        <circle v-bind="api.getCircleTrackProps()" />
        <circle v-bind="api.getCircleRangeProps()" />
      </svg>
      <div v-bind="api.getTrackProps()">
        <div v-bind="api.getRangeProps()" />
      </div>
      <div v-bind="api.getValueTextProps()">{{ api.valueAsString }}</div>
      <div>
        <button @click="() => api.setValue((api.value ?? 0) - 20)">Decrease</button>
        <button @click="() => api.setValue((api.value ?? 0) + 20)">Increase</button>
        <button @click="() => api.setValue(null)">Indeterminate</button>
      </div>
    </div>
  </main>

  <Toolbar>
    <StateVisualizer :state="service" />
    <template #controls>
      <Controls :control="controls" />
    </template>
  </Toolbar>
</template>
