// examples/next-ts/app/listbox/grid/page.tsx
"use client"

import * as listbox from "@zag-js/listbox"
import { normalizeProps, useMachine } from "@zag-js/react"
import { listboxControls, selectData } from "@zag-js/shared"
import { useId } from "react"
import { StateVisualizer } from "@/components/state-visualizer"
import { Toolbar } from "@/components/toolbar"
import { useControls } from "@/hooks/use-controls"
import "@styles/listbox.css"

interface Item {
  label: string
  value: string
}

export default function Page() {
  const controls = useControls(listboxControls)

  const collection = listbox.gridCollection({
    items: selectData,
    columnCount: 3,
  })

  const service = useMachine(listbox.machine as listbox.Machine<Item>, {
    collection,
    id: useId(),
    ...controls.context,
  })

  const api = listbox.connect(service, normalizeProps)

  return (
    <>
      <main className="listbox">
        <div {...api.getRootProps()}>
          <label {...api.getLabelProps()}>Label</label>
          <div {...api.getContentProps()}>
            <ul {...api.getListProps()}>
              {collection.items.map((item) => (
                <li key={item.value} {...api.getItemProps({ item })}>
                  {item.label}
                  <span {...api.getItemIndicatorProps({ item })}>✓</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </main>

      <Toolbar controls={controls.ui} viz>
        <StateVisualizer state={service} context={["highlightedValue"]} />
      </Toolbar>
    </>
  )
}

// examples/solid-ts/src/routes/listbox/grid.tsx
import * as listbox from "@zag-js/listbox"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { listboxControls, selectData } from "@zag-js/shared"
import { createMemo, createUniqueId, For } from "solid-js"
import { StateVisualizer } from "../../components/state-visualizer"
import { Toolbar } from "../../components/toolbar"
import { useControls } from "../../hooks/use-controls"
import "@styles/listbox.css"

interface Item {
  label: string
  value: string
}

export default function Page() {
  const controls = useControls(listboxControls)

  const collection = listbox.gridCollection({
    items: selectData,
    columnCount: 3,
  })

  const service = useMachine(
    listbox.machine as listbox.Machine<Item>,
    controls.mergeProps({
      collection,
      id: createUniqueId(),
    }),
  )

  const api = createMemo(() => listbox.connect(service, normalizeProps))

  return (
    <>
      <main class="listbox">
        <div {...api().getRootProps()}>
          <label {...api().getLabelProps()}>Label</label>
          <div {...api().getContentProps()}>
            <ul {...api().getListProps()}>
              <For each={collection.items}>
                {(item) => (
                  <li {...api().getItemProps({ item })}>
                    {item.label}
                    <span {...api().getItemIndicatorProps({ item })}>✓</span>
                  </li>
                )}
              </For>
            </ul>
          </div>
        </div>
      </main>

      <Toolbar controls={controls}>
        <StateVisualizer state={service} context={["highlightedValue"]} />
      </Toolbar>
    </>
  )
}
