// examples/solid-ts/src/routes/virtualizer/list.tsx
import { Index, createMemo, createSignal } from "solid-js"
import { useListVirtualizer } from "../../hooks/use-virtualizer"

const ITEM_COUNT = 10_000

const items = Array.from({ length: ITEM_COUNT }, (_, index) => ({
  id: `item-${index}`,
  name: `Item ${index + 1}`,
  description: `This is the description for item ${index + 1}`,
}))

export default function Page() {
  const [smoothScroll, setSmoothScroll] = createSignal(true)
  const { virtualizer, ref, version } = useListVirtualizer({
    count: ITEM_COUNT,
    estimatedSize: () => 64,
    overscan: 6,
  })

  const layout = createMemo(() => {
    version()
    return {
      virtualItems: virtualizer.getVirtualItems(),
      totalSize: virtualizer.getTotalSize(),
    }
  })

  return (
    <main style={{ padding: "20px", width: "100%", "max-width": "900px" }}>
      <h1>List Virtualizer</h1>
      <p style={{ color: "#64748b" }}>Efficiently render {ITEM_COUNT.toLocaleString()} rows.</p>

      <label
        style={{ display: "flex", "align-items": "center", gap: "8px", "margin-top": "12px", "user-select": "none" }}
      >
        <input
          type="checkbox"
          checked={smoothScroll()}
          onChange={(event) => setSmoothScroll(event.currentTarget.checked)}
        />
        Smooth scroll
      </label>

      <div style={{ display: "flex", gap: "8px", "flex-wrap": "wrap", "margin-top": "12px" }}>
        <button type="button" onClick={() => virtualizer.scrollToIndex(0, { smooth: smoothScroll() })}>
          Scroll to top
        </button>
        <button
          type="button"
          onClick={() =>
            virtualizer.scrollToIndex(Math.floor(ITEM_COUNT / 2), { align: "center", smooth: smoothScroll() })
          }
        >
          Scroll to middle
        </button>
        <button type="button" onClick={() => virtualizer.scrollToIndex(ITEM_COUNT - 1, { smooth: smoothScroll() })}>
          Scroll to bottom
        </button>
      </div>

      <div
        ref={ref}
        onScroll={virtualizer.handleScroll}
        {...virtualizer.getContainerAriaAttrs()}
        tabIndex={0}
        aria-label="Virtualized list"
        style={{
          ...virtualizer.getContainerStyle(),
          width: "100%",
          height: "420px",
          border: "1px solid #d1d5db",
          "border-radius": "8px",
          "margin-top": "16px",
        }}
      >
        <div style={{ height: `${layout().totalSize}px`, width: "100%", position: "relative" }}>
          <Index each={layout().virtualItems}>
            {(virtualItem) => (
              <div
                data-index={virtualItem().index}
                {...virtualizer.getItemAriaAttrs(virtualItem().index)}
                style={{
                  ...virtualizer.getItemStyle(virtualItem()),
                  padding: "12px 16px",
                  "border-bottom": "1px solid #e5e7eb",
                  background: virtualItem().index % 2 === 0 ? "#f8fafc" : "#fff",
                }}
              >
                <strong>{items[virtualItem().index].name}</strong>
                <p style={{ margin: "6px 0 0", color: "#64748b" }}>{items[virtualItem().index].description}</p>
              </div>
            )}
          </Index>
        </div>
      </div>
    </main>
  )
}

// examples/next-ts/pages/virtualizer/list.tsx
import { useState } from "react"
import { useListVirtualizer } from "../../hooks/use-virtualizer"

const generateItems = (count: number) =>
  Array.from({ length: count }, (_, i) => ({
    id: i,
    name: `Item ${i + 1}`,
    description: `This is the description for item ${i + 1}`,
  }))

const items = generateItems(10000)

export default function Page() {
  const [isSmooth, setIsSmooth] = useState(true)
  const { virtualizer, ref: setScrollElementRef } = useListVirtualizer({
    count: items.length,
    estimatedSize: () => 142,
    overscan: 5,
    gap: 0,
    paddingStart: 0,
    paddingEnd: 0,
  })

  const virtualItems = virtualizer.getVirtualItems()
  const totalSize = virtualizer.getTotalSize()

  return (
    <main className="list-virtualizer">
      <div style={{ padding: "20px" }}>
        <h1>List Virtualizer Example</h1>
        <p>Scrolling through {items.length.toLocaleString()} items efficiently</p>

        <label style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 12, userSelect: "none" }}>
          <input type="checkbox" checked={isSmooth} onChange={(e) => setIsSmooth(e.currentTarget.checked)} />
          Smooth scroll
        </label>

        <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 12 }}>
          <button type="button" onClick={() => virtualizer.scrollToIndex(0, { smooth: isSmooth })}>
            Scroll to Top
          </button>
          <button
            type="button"
            onClick={() =>
              virtualizer.scrollToIndex(Math.floor(items.length / 2), { align: "center", smooth: isSmooth })
            }
          >
            Scroll to Middle
          </button>
          <button type="button" onClick={() => virtualizer.scrollToIndex(items.length - 1, { smooth: isSmooth })}>
            Scroll to Bottom
          </button>
        </div>

        <div
          ref={setScrollElementRef}
          onScroll={virtualizer.handleScroll}
          {...virtualizer.getContainerAriaAttrs()}
          tabIndex={0}
          aria-label="Virtualized list"
          style={{
            ...virtualizer.getContainerStyle(),
            height: "400px",
            border: "1px solid #ccc",
            marginTop: "16px",
          }}
        >
          <div
            style={{
              height: `${totalSize}px`,
              width: "100%",
              position: "relative",
            }}
          >
            {virtualItems.map((virtualItem) => {
              const item = items[virtualItem.index]
              const style = virtualizer.getItemStyle(virtualItem)

              return (
                <div
                  key={virtualItem.index}
                  data-index={virtualItem.index}
                  {...virtualizer.getItemAriaAttrs(virtualItem.index)}
                  style={{
                    ...style,
                    padding: "16px",
                    backgroundColor: virtualItem.index % 2 === 0 ? "#f8f9fa" : "#ffffff",
                    borderBottom: "1px solid #e1e5e9",
                    display: "flex",
                    flexDirection: "column",
                    gap: "8px",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                      fontWeight: "600",
                      fontSize: "16px",
                      color: "#1a1a1a",
                    }}
                  >
                    {item.name}
                  </div>
                  <p>{item.description}</p>
                  <div
                    style={{
                      fontSize: "12px",
                      color: "#9ca3af",
                      fontFamily: "monospace",
                    }}
                  >
                    Virtual Index: {virtualItem.index} | Start: {virtualItem.start}px | Size: {virtualItem.size}px
                  </div>
                </div>
              )
            })}
          </div>
        </div>

        <div style={{ marginTop: "16px", fontSize: "14px", color: "#6b7280" }}>
          <div>Total items: {items.length.toLocaleString()}</div>
          <div>Rendered items: {virtualItems.length}</div>
          <div>Total height: {totalSize}px</div>
          <div>
            Visible range: {virtualItems[0]?.index ?? 0} - {virtualItems[virtualItems.length - 1]?.index ?? 0}
          </div>
          {virtualItems.length > 100 && (
            <div style={{ color: "orange" }}>⚠️ Many items rendered (fast scroll mode)</div>
          )}
          {virtualItems.length <= 100 && <div style={{ color: "green" }}>✅ Virtualization working!</div>}
        </div>
      </div>
    </main>
  )
}
