// examples/next-ts/pages/dialog/autofocus-attr.tsx
import * as dialog from "@zag-js/dialog"
import { Portal, normalizeProps, useMachine } from "@zag-js/react"
import { useId } from "react"

export default function Page() {
  const service = useMachine(dialog.machine, { id: useId() })
  const api = dialog.connect(service, normalizeProps)

  return (
    <main>
      <button {...api.getTriggerProps()}>Open dialog</button>
      {api.open && (
        <Portal>
          <div {...api.getBackdropProps()} />
          <div {...api.getPositionerProps()}>
            <div {...api.getContentProps()}>
              <button {...api.getCloseTriggerProps()}>Close</button>
              <h2 {...api.getTitleProps()}>Edit profile</h2>
              <p {...api.getDescriptionProps()}>The name input receives focus via data-autofocus.</p>
              <input data-autofocus placeholder="Enter name..." />
              <button>Save</button>
            </div>
          </div>
        </Portal>
      )}
    </main>
  )
}

// examples/nuxt-ts/app/pages/dialog/autofocus-attr.vue
<script lang="ts" setup>
import * as dialog from "@zag-js/dialog"
import { normalizeProps, useMachine } from "@zag-js/vue"

const service = useMachine(dialog.machine, { id: useId() })
const api = computed(() => dialog.connect(service, normalizeProps))
</script>

<template>
  <main>
    <button v-bind="api.getTriggerProps()">Open dialog</button>

    <Presence v-bind="api.getBackdropProps()" />
    <div v-bind="api.getPositionerProps()">
      <Presence v-bind="api.getContentProps()">
        <button v-bind="api.getCloseTriggerProps()">Close</button>
        <h2 v-bind="api.getTitleProps()">Edit profile</h2>
        <p v-bind="api.getDescriptionProps()">The name input receives focus via data-autofocus.</p>
        <input data-autofocus placeholder="Enter name..." />
        <button>Save</button>
      </Presence>
    </div>
  </main>
</template>
