// examples/solid-ts/src/routes/dialog/controlled.tsx
import * as dialog from "@zag-js/dialog"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { Show, createMemo, createSignal } from "solid-js"
import { Portal } from "solid-js/web"

export default function Page() {
  const [open, setOpen] = createSignal(false)

  const service = useMachine(dialog.machine, () => ({
    id: "1",
    open: open(),
    onOpenChange(details) {
      setOpen(details.open)
    },
  }))

  const api = createMemo(() => dialog.connect(service, normalizeProps))

  return (
    <div>
      <button onClick={() => setOpen(!open())}>Open Dialog</button>
      <p>state - isOpen: {String(open())}</p>
      <p>machine - isOpen: {String(api().open)}</p>
      <Show when={api().open}>
        <Portal>
          <div {...api().getBackdropProps()} />
          <div {...api().getPositionerProps()}>
            <div {...api().getContentProps()}>
              <h2 {...api().getTitleProps()}>Edit profile</h2>
              <p {...api().getDescriptionProps()}>Make changes to your profile here. Click save when you are done.</p>
              <div>
                <input placeholder="Enter name..." />
                <button>Save</button>
              </div>
              <button {...api().getCloseTriggerProps()}>Close</button>
            </div>
          </div>
        </Portal>
      </Show>
    </div>
  )
}

// examples/nuxt-ts/app/pages/dialog/controlled.vue
<script lang="ts" setup>
import * as dialog from "@zag-js/dialog"
import { normalizeProps, useMachine } from "@zag-js/vue"

const open = ref(false)

const service = useMachine(
  dialog.machine,
  computed(() => ({
    id: "1",
    open: open.value,
    onOpenChange(details) {
      open.value = details.open
    },
  })),
)

const api = computed(() => dialog.connect(service, normalizeProps))
</script>

<template>
  <div>
    <button @click="open = !open">Open Dialog</button>
    <p>state - isOpen: {{ String(open) }}</p>
    <p>machine - isOpen: {{ String(api.open) }}</p>
    <Teleport v-if="api.open" to="#teleports">
      <div v-bind="api.getBackdropProps()" />
      <div v-bind="api.getPositionerProps()">
        <div v-bind="api.getContentProps()">
          <h2 v-bind="api.getTitleProps()">Edit profile</h2>
          <p v-bind="api.getDescriptionProps()">Make changes to your profile here. Click save when you are done.</p>
          <div>
            <input placeholder="Enter name..." />
            <button>Save</button>
          </div>
          <button v-bind="api.getCloseTriggerProps()">Close</button>
        </div>
      </div>
    </Teleport>
  </div>
</template>
