// examples/next-ts/pages/menu/options.tsx
import styles from "../../../../shared/src/css/menu.module.css"
import * as menu from "@zag-js/menu"
import { normalizeProps, Portal, useMachine } from "@zag-js/react"
import { menuOptionData, menuControls } from "@zag-js/shared"
import { useId, useState } from "react"
import { StateVisualizer } from "../../components/state-visualizer"
import { Toolbar } from "../../components/toolbar"
import { useControls } from "../../hooks/use-controls"

export default function Page() {
  const controls = useControls(menuControls)

  const [order, setOrder] = useState("")
  const [type, setType] = useState<string[]>([])

  const service = useMachine(menu.machine, { id: useId() })
  const api = menu.connect(service, normalizeProps)

  const radios = menuOptionData.order.map((item) => ({
    type: "radio" as const,
    name: "order",
    value: item.value,
    label: item.label,
    checked: order === item.value,
    onCheckedChange: (checked: boolean) => setOrder(checked ? item.value : ""),
  }))

  const checkboxes = menuOptionData.type.map((item) => ({
    type: "checkbox" as const,
    name: "type",
    value: item.value,
    label: item.label,
    checked: type.includes(item.value),
    onCheckedChange: (checked: boolean) =>
      setType((prev) => (checked ? [...prev, item.value] : prev.filter((x) => x !== item.value))),
  }))

  return (
    <>
      <main>
        <div>
          <button data-testid="trigger" {...api.getTriggerProps()}>
            Actions <span {...api.getIndicatorProps()}>▾</span>
          </button>

          <Portal>
            <div {...api.getPositionerProps()}>
              <div {...api.getContentProps()} className={styles.Content}>
                {radios.map((item) => {
                  return (
                    <div key={item.value} {...api.getOptionItemProps(item)}>
                      <span {...api.getItemIndicatorProps(item)}>✅</span>
                      <span {...api.getItemTextProps(item)}>{item.label}</span>
                    </div>
                  )
                })}
                <hr />
                {checkboxes.map((item) => {
                  return (
                    <div key={item.value} {...api.getOptionItemProps(item)}>
                      <span {...api.getItemIndicatorProps(item)}>✅</span>
                      <span {...api.getItemTextProps(item)}>{item.label}</span>
                    </div>
                  )
                })}
              </div>
            </div>
          </Portal>
        </div>
      </main>

      <Toolbar controls={controls.ui}>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}

// examples/solid-ts/src/routes/menu/options.tsx
import styles from "../../../../../shared/src/css/menu.module.css"
import * as menu from "@zag-js/menu"
import { menuControls, menuOptionData } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { createMemo, createSignal, createUniqueId, For } from "solid-js"
import { Portal } from "solid-js/web"
import { StateVisualizer } from "~/components/state-visualizer"
import { Toolbar } from "~/components/toolbar"
import { useControls } from "~/hooks/use-controls"

export default function Page() {
  const controls = useControls(menuControls)

  const [order, setOrder] = createSignal("")
  const [type, setType] = createSignal<string[]>([])

  const service = useMachine(menu.machine, { id: createUniqueId() })
  const api = createMemo(() => menu.connect(service, normalizeProps))

  const radios = createMemo(() =>
    menuOptionData.order.map((item) => ({
      type: "radio" as const,
      value: item.value,
      label: item.label,
      checked: order() === item.value,
      onCheckedChange: (checked: boolean) => setOrder(checked ? item.value : ""),
    })),
  )

  const checkboxes = createMemo(() =>
    menuOptionData.type.map((item) => ({
      type: "checkbox" as const,
      value: item.value,
      label: item.label,
      checked: type().includes(item.value),
      onCheckedChange: (checked: boolean) =>
        setType((prev) => (checked ? [...prev, item.value] : prev.filter((x) => x !== item.value))),
    })),
  )

  return (
    <>
      <main>
        <div>
          <button data-testid="trigger" {...api().getTriggerProps()}>
            Actions <span {...api().getIndicatorProps()}>▾</span>
          </button>

          <Portal>
            <div {...api().getPositionerProps()}>
              <div {...api().getContentProps()} class={styles.Content}>
                <For each={radios()}>
                  {(item) => (
                    <div {...api().getOptionItemProps(item)}>
                      <span {...api().getItemIndicatorProps(item)}>✅</span>
                      <span {...api().getItemTextProps(item)}>{item.label}</span>
                    </div>
                  )}
                </For>
                <hr {...api().getSeparatorProps()} />
                <For each={checkboxes()}>
                  {(item) => (
                    <div {...api().getOptionItemProps(item)}>
                      <span {...api().getItemIndicatorProps(item)}>✅</span>
                      <span {...api().getItemTextProps(item)}>{item.label}</span>
                    </div>
                  )}
                </For>
              </div>
            </div>
          </Portal>
        </div>
      </main>

      <Toolbar controls={controls}>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}
