// examples/preact-ts/src/components/presence.tsx
import * as presence from "@zag-js/presence"
import { normalizeProps, useMachine } from "@zag-js/preact"
import { forwardRef, Ref } from "preact/compat"
import { useEffect, useRef, useState } from "preact/hooks"
import { JSX } from "preact"

interface PresenceProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /**
   * Whether to enable lazy mounting.
   */
  lazyMount?: boolean
  /**
   * Whether to skip the initial mount animation.
   */
  skipAnimationOnMount?: boolean
  /**
   * Whether to unmount the component when it's not present.
   */
  unmountOnExit?: boolean
}

export const Presence = forwardRef<HTMLDivElement, PresenceProps>(function Presence(props, ref) {
  const { hidden, lazyMount, skipAnimationOnMount, unmountOnExit, ...rest } = props

  const present = !hidden
  const service = useMachine(presence.machine, { present })
  const api = presence.connect(service, normalizeProps)

  const [wasEverPresent, setWasEverPresent] = useState(false)

  useEffect(() => {
    if (api.present) setWasEverPresent(true)
  }, [api.present])

  const internalRef = useRef<HTMLDivElement>(null)
  const mergedRef: Ref<HTMLDivElement> = (node) => {
    internalRef.current = node
    if (typeof ref === "function") {
      ref(node)
    } else if (ref) {
      ref.current = node
    }
  }

  useEffect(() => {
    if (internalRef.current) {
      api.setNode(internalRef.current)
    }
  }, [])

  const unmounted = (!api.present && !wasEverPresent && lazyMount) || (unmountOnExit && !api.present && wasEverPresent)

  if (unmounted) return null

  return (
    <div
      ref={mergedRef}
      data-scope="presence"
      data-state={api.skip && skipAnimationOnMount ? undefined : present ? "open" : "closed"}
      hidden={!api.present}
      {...rest}
    />
  )
})

// examples/solid-ts/src/components/presence.tsx
import * as presence from "@zag-js/presence"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { JSX, createMemo, createSignal, mergeProps, onMount, splitProps } from "solid-js"

interface PresenceProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /**
   * Whether to enable lazy mounting.
   */
  lazyMount?: boolean
  /**
   * Whether to skip the initial mount animation.
   */
  skipAnimationOnMount?: boolean
  /**
   * Whether to unmount the component when it's not present.
   */
  unmountOnExit?: boolean
}

export function Presence(props: PresenceProps) {
  const [localProps, restProps] = splitProps(props, [
    "hidden",
    "ref",
    "lazyMount",
    "skipAnimationOnMount",
    "unmountOnExit",
  ])
  const present = createMemo(() => !localProps.hidden)

  const service = useMachine(
    presence.machine,
    createMemo(() => ({ present: present() })),
  )
  const api = createMemo(() => presence.connect(service, normalizeProps))

  const [wasEverPresent, setWasEverPresent] = createSignal(false)

  createMemo(() => {
    if (api().present) setWasEverPresent(true)
  })

  let ref: HTMLDivElement | undefined

  onMount(() => {
    if (ref) {
      api().setNode(ref)
    }
  })

  const mergedRef = (el: HTMLDivElement) => {
    ref = el
    if (typeof localProps.ref === "function") {
      localProps.ref(el)
    } else if (localProps.ref) {
      localProps.ref = el
    }
  }

  const unmounted = createMemo(() => {
    if (!api().present && !wasEverPresent() && localProps.lazyMount) return true
    if (localProps.unmountOnExit && !api().present && wasEverPresent()) return true
    return false
  })

  const mergedProps = createMemo(() =>
    mergeProps(
      {
        ref: mergedRef,
        "data-scope": "presence",
        "data-state": api().skip && localProps.skipAnimationOnMount ? undefined : present() ? "open" : "closed",
        hidden: !api().present,
      },
      restProps,
    ),
  )

  return <>{!unmounted() && <div {...mergedProps()} />}</>
}
