// examples/nuxt-ts/app/pages/number-input/scrubber.vue
<script setup lang="ts">
import * as numberInput from "@zag-js/number-input"
import { numberInputControls } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/vue"
import { MoveHorizontalIcon } from "lucide-vue-next"
import "@styles/number-input.css"

const controls = useControls(numberInputControls)

const service = useMachine(
  numberInput.machine,
  controls.mergeProps<numberInput.Props>({
    id: useId(),
  }),
)

const api = computed(() => numberInput.connect(service, normalizeProps))
</script>

<template>
  <main>
    <div v-bind="api.getRootProps()">
      <div data-testid="scrubber" v-bind="api.getScrubberProps()">
        <span v-bind="api.getScrubberCursorProps()">
          <MoveHorizontalIcon />
        </span>
      </div>
      <label data-testid="label" v-bind="api.getLabelProps()"> Enter number </label>
      <div v-bind="api.getControlProps()">
        <button data-testid="dec-button" v-bind="api.getDecrementTriggerProps()">DEC</button>
        <input data-testid="input" v-bind="api.getInputProps()" />
        <button data-testid="inc-button" v-bind="api.getIncrementTriggerProps()">INC</button>
      </div>
    </div>
  </main>

  <Toolbar>
    <StateVisualizer :state="service" :omit="['formatter', 'parser']" />
    <template #controls>
      <Controls :control="controls" />
    </template>
  </Toolbar>
</template>

// examples/preact-ts/src/pages/number-input/scrubber.tsx
import * as numberInput from "@zag-js/number-input"
import { normalizeProps, useMachine } from "@zag-js/preact"
import { numberInputControls } from "@zag-js/shared"
import { MoveHorizontalIcon } from "lucide-preact"
import { useId } from "react"
import { useControls } from "../../hooks/use-controls"
import { Toolbar } from "../../components/toolbar"
import { StateVisualizer } from "../../components/state-visualizer"
import "@styles/number-input.css"

export default function NumberInput() {
  const controls = useControls(numberInputControls)

  const service = useMachine(numberInput.machine, {
    id: useId(),
    ...controls.context,
  })

  const api = numberInput.connect(service, normalizeProps)

  return (
    <>
      <main>
        <div {...api.getRootProps()}>
          <div data-testid="scrubber" {...api.getScrubberProps()}>
            <span {...api.getScrubberCursorProps()}>
              <MoveHorizontalIcon />
            </span>
          </div>
          <label data-testid="label" {...api.getLabelProps()}>
            Enter number:
          </label>
          <div {...api.getControlProps()}>
            <button data-testid="dec-button" {...api.getDecrementTriggerProps()}>
              DEC
            </button>
            <input data-testid="input" {...api.getInputProps()} />
            <button data-testid="inc-button" {...api.getIncrementTriggerProps()}>
              INC
            </button>
          </div>
        </div>
      </main>

      <Toolbar controls={controls.ui}>
        <StateVisualizer state={service} omit={["formatter", "parser"]} />
      </Toolbar>
    </>
  )
}
