// examples/next-ts/pages/floating-panel/popover-inside.tsx
import * as floating from "@zag-js/floating-panel"
import * as popover from "@zag-js/popover"
import { normalizeProps, Portal, useMachine } from "@zag-js/react"
import { ArrowDownLeft, Maximize2, Minus, XIcon } from "lucide-react"
import { Fragment, useId } from "react"
import { StateVisualizer } from "../../components/state-visualizer"
import { Toolbar } from "../../components/toolbar"

export default function Page() {
  const service = useMachine(floating.machine, {
    id: useId(),
    closeOnEscape: true,
    defaultSize: { width: 400, height: 300 },
  })

  const api = floating.connect(service, normalizeProps)

  return (
    <>
      <main className="floating-panel">
        <div>
          <button {...api.getTriggerProps()}>Toggle Panel</button>
          <div {...api.getPositionerProps()}>
            <div {...api.getContentProps()}>
              <div {...api.getDragTriggerProps()}>
                <div {...api.getHeaderProps()}>
                  <p {...api.getTitleProps()}>Floating Panel (Nested Popover)</p>
                  <div {...api.getControlProps()}>
                    <button {...api.getStageTriggerProps({ stage: "minimized" })}>
                      <Minus />
                    </button>
                    <button {...api.getStageTriggerProps({ stage: "maximized" })}>
                      <Maximize2 />
                    </button>
                    <button {...api.getStageTriggerProps({ stage: "default" })}>
                      <ArrowDownLeft />
                    </button>
                    <button {...api.getCloseTriggerProps()}>
                      <XIcon />
                    </button>
                  </div>
                </div>
              </div>
              <div {...api.getBodyProps()}>
                <p>Escape closes the popover first, then the panel.</p>
                <Popover />
              </div>

              {floating.resizeTriggerAxes.map((axis) => (
                <div key={axis} {...api.getResizeTriggerProps({ axis })} />
              ))}
            </div>
          </div>
        </div>
      </main>

      <Toolbar>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}

function Popover() {
  const service = useMachine(popover.machine, {
    id: useId(),
    portalled: false,
  })

  const api = popover.connect(service, normalizeProps)
  const Wrapper = api.portalled ? Portal : Fragment

  return (
    <div>
      <button {...api.getTriggerProps()}>Open Popover</button>
      <Wrapper>
        <div {...api.getPositionerProps()}>
          <div {...api.getContentProps()}>
            <div {...api.getTitleProps()}>Nested Popover</div>
            <div {...api.getDescriptionProps()}>Press Escape to close this popover without closing the panel.</div>
            <button {...api.getCloseTriggerProps()}>Close Popover</button>
          </div>
        </div>
      </Wrapper>
    </div>
  )
}

// examples/nuxt-ts/app/pages/floating-panel/popover-inside.vue
<script setup lang="ts">
import * as floatingPanel from "@zag-js/floating-panel"
import * as popover from "@zag-js/popover"
import { normalizeProps, useMachine } from "@zag-js/vue"
import { Minus, Maximize2, ArrowDownLeft, XIcon } from "lucide-vue-next"

const service = useMachine(floatingPanel.machine, {
  id: useId(),
  closeOnEscape: true,
  defaultSize: { width: 400, height: 300 },
})

const api = computed(() => floatingPanel.connect(service, normalizeProps))

const popoverService = useMachine(popover.machine, {
  id: useId(),
  portalled: false,
})

const popoverApi = computed(() => popover.connect(popoverService, normalizeProps))
</script>

<template>
  <main class="floating-panel">
    <div>
      <button v-bind="api.getTriggerProps()">Toggle Panel</button>
      <div v-bind="api.getPositionerProps()">
        <div v-bind="api.getContentProps()">
          <div v-bind="api.getDragTriggerProps()">
            <div v-bind="api.getHeaderProps()">
              <p v-bind="api.getTitleProps()">Floating Panel (Nested Popover)</p>
              <div v-bind="api.getControlProps()">
                <button v-bind="api.getStageTriggerProps({ stage: 'minimized' })">
                  <Minus />
                </button>
                <button v-bind="api.getStageTriggerProps({ stage: 'maximized' })">
                  <Maximize2 />
                </button>
                <button v-bind="api.getStageTriggerProps({ stage: 'default' })">
                  <ArrowDownLeft />
                </button>
                <button v-bind="api.getCloseTriggerProps()">
                  <XIcon />
                </button>
              </div>
            </div>
          </div>
          <div v-bind="api.getBodyProps()">
            <p>Escape closes the popover first, then the panel.</p>
            <div>
              <button v-bind="popoverApi.getTriggerProps()">Open Popover</button>
              <div v-bind="popoverApi.getPositionerProps()">
                <div v-bind="popoverApi.getContentProps()">
                  <div v-bind="popoverApi.getTitleProps()">Nested Popover</div>
                  <div v-bind="popoverApi.getDescriptionProps()">
                    Press Escape to close this popover without closing the panel.
                  </div>
                  <button v-bind="popoverApi.getCloseTriggerProps()">Close Popover</button>
                </div>
              </div>
            </div>
          </div>

          <div
            v-for="axis in floatingPanel.resizeTriggerAxes"
            :key="axis"
            v-bind="api.getResizeTriggerProps({ axis })"
          />
        </div>
      </div>
    </div>
  </main>

  <Toolbar>
    <StateVisualizer :state="service" />
  </Toolbar>
</template>
