// examples/nuxt-ts/app/pages/scroll-area/nested.vue
<script setup lang="ts">
import "@styles/scroll-area.css"
</script>

<template>
  <main class="scroll-area">
    <ScrollArea style="height: 500px; width: 800px">
      <ScrollArea v-for="i in 5" :key="i" style="max-height: 200px">
        <div v-for="j in 100" :key="j">{{ j }}</div>
      </ScrollArea>
    </ScrollArea>
  </main>
</template>

// examples/svelte-ts/src/routes/scroll-area/nested/+page.svelte
<script lang="ts">
  import ScrollArea from "$lib/components/scroll-area.svelte"
  import "@styles/scroll-area.css"
</script>

<main class="scroll-area">
  <ScrollArea style="height: 500px; width: 800px">
    {#each Array.from({ length: 5 }) as _, outerIndex (outerIndex)}
      <ScrollArea style="max-height: 200px">
        {#each Array.from({ length: 100 }) as _, index (index)}
          <div>{index}</div>
        {/each}
      </ScrollArea>
    {/each}
  </ScrollArea>
</main>
