// examples/nuxt-ts/pages/angle-slider.vue
<script setup lang="ts">
import * as angleSlider from "@zag-js/angle-slider"
import { angleSliderControls } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/vue"

const controls = useControls(angleSliderControls)

const service = useMachine(angleSlider.machine, { id: useId() })

const api = computed(() => angleSlider.connect(service, normalizeProps))
</script>

<template>
  <main class="angle-slider">
    <div v-bind="api.getRootProps()">
      <label v-bind="api.getLabelProps()">
        Angle Slider:
        <div v-bind="api.getValueTextProps()">{{ api.valueAsDegree }}</div>
      </label>
      <div v-bind="api.getControlProps()">
        <div v-bind="api.getThumbProps()"></div>
        <div v-bind="api.getMarkerGroupProps()">
          <div
            v-for="value in [0, 45, 90, 135, 180, 225, 270, 315]"
            :key="value"
            v-bind="api.getMarkerProps({ value })"
          ></div>
        </div>
      </div>
      <input v-bind="api.getHiddenInputProps()" />
    </div>
  </main>

  <Toolbar>
    <StateVisualizer :state="service" />
    <template #controls>
      <Controls :control="controls" />
    </template>
  </Toolbar>
</template>

// examples/next-ts/pages/angle-slider.tsx
import * as angleSlider from "@zag-js/angle-slider"
import { useMachine, normalizeProps } from "@zag-js/react"
import { angleSliderControls } from "@zag-js/shared"
import { useId } from "react"
import { StateVisualizer } from "../components/state-visualizer"
import { Toolbar } from "../components/toolbar"
import { useControls } from "../hooks/use-controls"

export default function Page() {
  const controls = useControls(angleSliderControls)

  const service = useMachine(angleSlider.machine, {
    id: useId(),
  })

  const api = angleSlider.connect(service, normalizeProps)

  return (
    <>
      <main className="angle-slider">
        <div {...api.getRootProps()}>
          <label {...api.getLabelProps()}>
            Angle Slider: <div {...api.getValueTextProps()}>{api.valueAsDegree}</div>
          </label>
          <div {...api.getControlProps()}>
            <div {...api.getThumbProps()}></div>
            <div {...api.getMarkerGroupProps()}>
              {[0, 45, 90, 135, 180, 225, 270, 315].map((value) => (
                <div key={value} {...api.getMarkerProps({ value })}></div>
              ))}
            </div>
          </div>
          <input {...api.getHiddenInputProps()} />
        </div>
      </main>

      <Toolbar controls={controls.ui}>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}
