// examples/solid-ts/src/pages/dialog-default-open.tsx
import { Portal } from "solid-js/web"
import * as dialog from "@zag-js/dialog"
import { useMachine, normalizeProps } from "@zag-js/solid"
import { StateVisualizer } from "../components/state-visualizer"
import { createMemo, createUniqueId } from "solid-js"
import { Toolbar } from "../components/toolbar"

export default function Page() {
  // dialog 1
  const [state, send] = useMachine(dialog.machine({ id: createUniqueId(), defaultOpen: true }))

  const parentDialog = createMemo(() => dialog.connect(state, send, normalizeProps))

  return (
    <>
      <main>
        <div>
          <button {...parentDialog().triggerProps} data-testid="trigger-1">
            Open Dialog
          </button>
          <div style={{ "min-height": "1200px" }} />
          {parentDialog().isOpen && (
            <Portal>
              <div class="dialog-backdrop" {...parentDialog().backdropProps} />
              <div {...parentDialog().containerProps} data-testid="container-1">
                <div {...parentDialog().contentProps}>
                  <h2 {...parentDialog().titleProps}>Edit profile</h2>
                  <p {...parentDialog().descriptionProps}>
                    Make changes to your profile here. Click save when you are done.
                  </p>
                  <button {...parentDialog().closeButtonProps} data-testid="close-1">
                    X
                  </button>
                  <input type="text" placeholder="Enter name..." data-testid="input-1" />
                  <button data-testid="save-button-1">Save Changes</button>
                </div>
              </div>
            </Portal>
          )}
        </div>
      </main>
      <Toolbar controls={null} visualizer={<StateVisualizer state={state} />} />
    </>
  )
}

// examples/next-ts/pages/dialog-default-open.tsx
import * as dialog from "@zag-js/dialog"
import { normalizeProps, useMachine, Portal } from "@zag-js/react"
import { useId, useRef } from "react"
import { StateVisualizer } from "../components/state-visualizer"
import { Toolbar } from "../components/toolbar"

export default function Page() {
  const inputRef = useRef<HTMLInputElement>(null)

  const [state, send] = useMachine(
    dialog.machine({
      id: useId(),
      defaultOpen: true,
    }),
  )
  const api = dialog.connect(state, send, normalizeProps)

  return (
    <>
      <main>
        <div>
          <button {...api.triggerProps} data-testid="trigger-1">
            Open Dialog
          </button>

          <div style={{ minHeight: "1200px" }} />

          {api.isOpen && (
            <Portal>
              <div className="dialog-backdrop" {...api.backdropProps} />
              <div data-testid="container-1" {...api.containerProps}>
                <div {...api.contentProps}>
                  <h2 {...api.titleProps}>Edit profile</h2>
                  <p {...api.descriptionProps}>Make changes to your profile here. Click save when you are done.</p>
                  <button {...api.closeButtonProps} data-testid="close-1">
                    X
                  </button>
                  <input type="text" ref={inputRef} placeholder="Enter name..." data-testid="input-1" />
                  <button data-testid="save-button">Save Changes</button>
                </div>
              </div>
            </Portal>
          )}
        </div>
      </main>
      <Toolbar controls={null}>
        <StateVisualizer label="Dialog 1" state={state} />
      </Toolbar>
    </>
  )
}
