// examples/nuxt-ts/app/pages/drawer.vue
<script setup lang="ts">
import * as drawer from "@zag-js/drawer"
import { drawerControls } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/vue"
import styles from "../../../shared/styles/drawer.module.css"

const controls = useControls(drawerControls)

const service = useMachine(
  drawer.machine,
  controls.mergeProps<drawer.Props>({
    id: useId(),
  }),
)

const api = computed(() => drawer.connect(service, normalizeProps))
</script>

<template>
  <main>
    <button :class="styles.trigger" v-bind="api.getTriggerProps()">Open</button>
    <div :class="styles.backdrop" v-bind="api.getBackdropProps()"></div>
    <div :class="styles.positioner" v-bind="api.getPositionerProps()">
      <div :class="styles.content" v-bind="api.getContentProps()">
        <div :class="styles.grabber" v-bind="api.getGrabberProps()">
          <div :class="styles.grabberIndicator" v-bind="api.getGrabberIndicatorProps()"></div>
        </div>
        <div v-bind="api.getTitleProps()">Drawer</div>
        <div data-no-drag="true" :class="styles.noDrag">No drag area</div>
        <div :class="styles.scrollable">
          <div v-for="(_element, index) in Array.from({ length: 100 })" :key="index">Item {{ index }}</div>
        </div>
      </div>
    </div>
  </main>

  <Toolbar>
    <StateVisualizer :state="service" />
    <template #controls>
      <Controls :control="controls" />
    </template>
  </Toolbar>
</template>

// examples/next-ts/pages/drawer.tsx
import * as drawer from "@zag-js/drawer"
import { normalizeProps, useMachine } from "@zag-js/react"
import { drawerControls } from "@zag-js/shared"
import { useId } from "react"
import { Presence } from "../components/presence"
import { StateVisualizer } from "../components/state-visualizer"
import { Toolbar } from "../components/toolbar"
import { useControls } from "../hooks/use-controls"
import styles from "../../shared/styles/drawer.module.css"

export default function Page() {
  const controls = useControls(drawerControls)

  const service = useMachine(drawer.machine, {
    id: useId(),
    ...controls.context,
  })

  const api = drawer.connect(service, normalizeProps)

  return (
    <>
      <main>
        <button className={styles.trigger} {...api.getTriggerProps()}>
          Open
        </button>
        <Presence className={styles.backdrop} {...api.getBackdropProps()} />
        <div className={styles.positioner} {...api.getPositionerProps()}>
          <Presence className={styles.content} {...api.getContentProps()}>
            <div className={styles.grabber} {...api.getGrabberProps()}>
              <div className={styles.grabberIndicator} {...api.getGrabberIndicatorProps()} />
            </div>
            <div {...api.getTitleProps()}>Drawer</div>
            <div data-no-drag className={styles.noDrag}>
              No drag area
            </div>
            <div className={styles.scrollable}>
              {Array.from({ length: 100 }).map((_element, index) => (
                <div key={index}>Item {index}</div>
              ))}
            </div>
          </Presence>
        </div>
      </main>

      <Toolbar controls={controls.ui}>
        <StateVisualizer state={service} context={["dragOffset", "snapPoint", "resolvedActiveSnapPoint"]} />
      </Toolbar>
    </>
  )
}
