// examples/vue-ts/src/pages/nested-nav-menu.tsx
import * as navMenu from "@zag-js/nav-menu"
import { nestedNavMenuData } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/vue"
import { StateVisualizer } from "../components/state-visualizer"
import { Toolbar } from "../components/toolbar"
import { computed, defineComponent, onMounted } from "vue"

export default defineComponent({
  name: "nested-nav-menu",
  setup() {
    const [state, send, machine] = useMachine(navMenu.machine({ id: "1" }))
    const root = computed(() => navMenu.connect(state.value, send, normalizeProps))

    const [subState, subSend, subMachine] = useMachine(navMenu.machine({ id: "2" }))
    const sub = computed(() => navMenu.connect(subState.value, subSend, normalizeProps))

    onMounted(() => {
      root.value.setChild(subMachine)
      sub.value.setParent(machine)
    })

    const getTriggerItemProps = (id: string) => computed(() => root.value.getTriggerMenuItemProps(sub.value, id))

    return () => {
      return (
        <>
          <main class="nav-menu">
            <nav {...root.value.rootProps}>
              <ul style={{ display: "flex", listStyle: "none" }}>
                {nestedNavMenuData.map(({ menu, menuList }) => (
                  <li key={menu.id}>
                    <button data-testid={`${menu.id}:trigger`} {...root.value.getTriggerProps({ id: menu.id })}>
                      {menu.label} <span {...root.value.indicatorProps}>▾</span>
                    </button>
                    <div {...root.value.getPositionerProps({ id: menu.id })}>
                      <ul data-testid={`${menu.id}:content`} {...root.value.getContentProps({ id: menu.id })}>
                        {menuList.map((item) => {
                          const { id, label, href, subList } = item
                          const hasSubList = !!subList
                          return (
                            <li key={JSON.stringify(item)}>
                              {hasSubList ? (
                                <>
                                  <button data-testid={`${id}:trigger`} {...getTriggerItemProps(id).value}>
                                    {label}
                                    <span {...sub.value.indicatorProps}>→</span>
                                  </button>
                                  <ul
                                    data-testid={`${id}:content`}
                                    {...sub.value.getContentProps({ id })}
                                    style={{ listStyle: "none" }}
                                  >
                                    {subList.map((item) => (
                                      <li key={JSON.stringify(item)}>
                                        <a
                                          data-testid={`${item.id}:menu-item`}
                                          {...sub.value.getMenuItemProps({ id: item.id, href: item.href })}
                                        >
                                          {item.label}
                                        </a>
                                      </li>
                                    ))}
                                  </ul>
                                </>
                              ) : (
                                <a
                                  data-testid={`${item.id}:menu-item`}
                                  {...root.value.getMenuItemProps({ id, href: href! })}
                                >
                                  {label}
                                </a>
                              )}
                            </li>
                          )
                        })}
                      </ul>
                    </div>
                  </li>
                ))}
              </ul>
            </nav>
          </main>

          <Toolbar controls={null}>
            <StateVisualizer state={state} />
            <StateVisualizer state={subState} />
          </Toolbar>
        </>
      )
    }
  },
})

// examples/next-ts/pages/nested-nav-menu.tsx
import * as navMenu from "@zag-js/nav-menu"
import { useMachine, normalizeProps } from "@zag-js/react"
import { nestedNavMenuData } from "@zag-js/shared"
import { useId } from "react"
import { StateVisualizer } from "../components/state-visualizer"
import { Toolbar } from "../components/toolbar"
import { useEffectOnce } from "../hooks/use-effect-once"

export default function Page() {
  const [state, send, machine] = useMachine(navMenu.machine({ id: useId() }))
  const root = navMenu.connect(state, send, normalizeProps)

  const [subState, subSend, subMachine] = useMachine(navMenu.machine({ id: useId() }))
  const sub = navMenu.connect(subState, subSend, normalizeProps)

  useEffectOnce(() => {
    root.setChild(subMachine)
    sub.setParent(machine)
  })

  const getTriggerItemProps = (id: string) => root.getTriggerMenuItemProps(sub, id)

  return (
    <>
      <main className="nav-menu">
        <nav {...root.rootProps}>
          <ul style={{ display: "flex", listStyle: "none" }}>
            {nestedNavMenuData.map(({ menu, menuList }) => (
              <li key={menu.id}>
                <button data-testid={`${menu.id}:trigger`} {...root.getTriggerProps({ id: menu.id })}>
                  {menu.label} <span {...root.indicatorProps}>▾</span>
                </button>
                <div {...root.getPositionerProps({ id: menu.id })}>
                  <ul data-testid={`${menu.id}:content`} {...root.getContentProps({ id: menu.id })}>
                    {menuList.map((item) => {
                      const { id, label, href, subList } = item
                      const hasSubList = !!subList
                      return (
                        <li key={JSON.stringify(item)}>
                          {hasSubList ? (
                            <>
                              <button data-testid={`${id}:trigger`} {...getTriggerItemProps(id)}>
                                {label}
                                <span {...sub.indicatorProps}>→</span>
                              </button>
                              <ul
                                data-testid={`${id}:content`}
                                {...sub.getContentProps({ id })}
                                style={{ listStyle: "none" }}
                              >
                                {subList.map((item) => (
                                  <li key={JSON.stringify(item)}>
                                    <a
                                      data-testid={`${item.id}:menu-item`}
                                      {...sub.getMenuItemProps({ id: item.id, href: item.href })}
                                    >
                                      {item.label}
                                    </a>
                                  </li>
                                ))}
                              </ul>
                            </>
                          ) : (
                            <a data-testid={`${item.id}:menu-item`} {...root.getMenuItemProps({ id, href })}>
                              {label}
                            </a>
                          )}
                        </li>
                      )
                    })}
                  </ul>
                </div>
              </li>
            ))}
          </ul>
        </nav>
      </main>

      <Toolbar controls={null}>
        <StateVisualizer state={state} label="Root machine" />
        <StateVisualizer state={subState} label="Sub machine" />
      </Toolbar>
    </>
  )
}
