// examples/svelte-ts/src/lib/components/floating-panel-stack-item.svelte
<script lang="ts">
  import * as floatingPanel from "@zag-js/floating-panel"
  import { normalizeProps, useMachine } from "@zag-js/svelte"
  import { XIcon } from "lucide-svelte"

  interface Props {
    name: string
    offset: number
  }

  const { name, offset }: Props = $props()

  const id = $props.id()
  const service = useMachine(floatingPanel.machine, {
    id,
    defaultPosition: { x: 100 + offset, y: 100 + offset },
  })

  const api = $derived(floatingPanel.connect(service, normalizeProps))
</script>

<div>
  <button {...api.getTriggerProps()} data-testid={`trigger-${name}`}>
    Toggle {name}
  </button>
  <div {...api.getPositionerProps()} data-testid={`positioner-${name}`}>
    <div {...api.getContentProps()} data-testid={`content-${name}`}>
      <div {...api.getDragTriggerProps()}>
        <div {...api.getHeaderProps()}>
          <p {...api.getTitleProps()}>Panel {name}</p>
          <div {...api.getControlProps()}>
            <button {...api.getCloseTriggerProps()} data-testid={`close-${name}`}>
              <XIcon />
            </button>
          </div>
        </div>
      </div>
      <div {...api.getBodyProps()}>
        <p>Content {name}</p>
      </div>
    </div>
  </div>
</div>

// examples/nuxt-ts/app/components/FloatingPanelStackItem.vue
<script setup lang="ts">
import * as floatingPanel from "@zag-js/floating-panel"
import { normalizeProps, useMachine } from "@zag-js/vue"
import { XIcon } from "lucide-vue-next"

const props = defineProps<{ name: string; offset: number }>()

const service = useMachine(floatingPanel.machine, {
  id: useId(),
  defaultPosition: { x: 100 + props.offset, y: 100 + props.offset },
})

const api = computed(() => floatingPanel.connect(service, normalizeProps))
</script>

<template>
  <div>
    <button v-bind="api.getTriggerProps()" :data-testid="`trigger-${name}`">Toggle {{ name }}</button>
    <div v-bind="api.getPositionerProps()" :data-testid="`positioner-${name}`">
      <div v-bind="api.getContentProps()" :data-testid="`content-${name}`">
        <div v-bind="api.getDragTriggerProps()">
          <div v-bind="api.getHeaderProps()">
            <p v-bind="api.getTitleProps()">Panel {{ name }}</p>
            <div v-bind="api.getControlProps()">
              <button v-bind="api.getCloseTriggerProps()" :data-testid="`close-${name}`">
                <XIcon />
              </button>
            </div>
          </div>
        </div>
        <div v-bind="api.getBodyProps()">
          <p>Content {{ name }}</p>
        </div>
      </div>
    </div>
  </div>
</template>
