// examples/next-ts/pages/nested-menu.tsx
import * as menu from "@zag-js/menu"
import { normalizeProps, Portal, useMachine } from "@zag-js/react"
import { menuData } from "@zag-js/shared"
import { useEffect, useId } from "react"
import { StateVisualizer } from "../components/state-visualizer"
import { Toolbar } from "../components/toolbar"

export default function Page() {
  const [state, send, machine] = useMachine(
    menu.machine({
      id: useId(),
    }),
  )
  const root = menu.connect(state, send, normalizeProps)

  const [subState, subSend, subMachine] = useMachine(
    menu.machine({
      id: useId(),
    }),
  )
  const sub = menu.connect(subState, subSend, normalizeProps)

  const [sub2State, sub2Send, sub2Machine] = useMachine(
    menu.machine({
      id: useId(),
    }),
  )
  const sub2 = menu.connect(sub2State, sub2Send, normalizeProps)

  useEffect(() => {
    root.setChild(subMachine)
    sub.setParent(machine)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    sub.setChild(sub2Machine)
    sub2.setParent(subMachine)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const triggerItemProps = root.getTriggerItemProps(sub)
  const triggerItem2Props = sub.getTriggerItemProps(sub2)

  const [level1, level2, level3] = menuData

  return (
    <>
      <main>
        <div>
          <button data-testid="trigger" {...root.triggerProps}>
            Click me
          </button>

          <Portal>
            <div {...root.positionerProps}>
              <ul data-testid="menu" className="menu-content" {...root.contentProps}>
                {level1.map((item) => {
                  const props = item.trigger ? triggerItemProps : root.getItemProps({ id: item.id })
                  return (
                    <li key={item.id} data-testid={item.id} {...props}>
                      {item.label}
                    </li>
                  )
                })}
              </ul>
            </div>
          </Portal>

          <Portal>
            <div {...sub.positionerProps}>
              <ul data-testid="more-tools-submenu" className="menu-content" {...sub.contentProps}>
                {level2.map((item) => {
                  const props = item.trigger ? triggerItem2Props : sub.getItemProps({ id: item.id })
                  return (
                    <li key={item.id} data-testid={item.id} {...props}>
                      {item.label}
                    </li>
                  )
                })}
              </ul>
            </div>
          </Portal>

          <Portal>
            <div {...sub2.positionerProps}>
              <ul data-testid="open-nested-submenu" className="menu-content" {...sub2.contentProps}>
                {level3.map((item) => (
                  <li key={item.id} data-testid={item.id} {...sub2.getItemProps({ id: item.id })}>
                    {item.label}
                  </li>
                ))}
              </ul>
            </div>
          </Portal>
        </div>
      </main>

      <Toolbar controls={null}>
        <StateVisualizer state={state} label="Root Machine" />
        <StateVisualizer state={subState} label="Sub Machine" />
        <StateVisualizer state={sub2State} label="Sub2 Machine" />
      </Toolbar>
    </>
  )
}

// examples/solid-ts/src/pages/nested-menu.tsx
import * as menu from "@zag-js/menu"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { createMemo, createUniqueId, For, onMount } from "solid-js"
import { Portal } from "solid-js/web"
import { menuData } from "@zag-js/shared"
import { StateVisualizer } from "../components/state-visualizer"
import { Toolbar } from "../components/toolbar"

export default function Page() {
  const [state, send, machine] = useMachine(menu.machine({ id: createUniqueId() }))

  const root = createMemo(() => menu.connect(state, send, normalizeProps))

  const [subState, subSend, subMachine] = useMachine(menu.machine({ id: createUniqueId() }))
  const sub = createMemo(() => menu.connect(subState, subSend, normalizeProps))

  const [sub2State, sub2Send, sub2Machine] = useMachine(menu.machine({ id: createUniqueId() }))
  const sub2 = createMemo(() => menu.connect(sub2State, sub2Send, normalizeProps))

  onMount(() => {
    root().setChild(subMachine)
    sub().setParent(machine)
  })

  onMount(() => {
    sub().setChild(sub2Machine)
    sub2().setParent(subMachine)
  })

  const triggerItemProps = createMemo(() => root().getTriggerItemProps(sub()))
  const triggerItem2Props = createMemo(() => sub().getTriggerItemProps(sub2()))

  const [level1, level2, level3] = menuData

  return (
    <>
      <main>
        <div>
          <button data-testid="trigger" {...root().triggerProps}>
            Click me
          </button>

          <Portal>
            <div {...root().positionerProps}>
              <ul data-testid="menu" class="menu-content" {...root().contentProps}>
                <For each={level1}>
                  {(item) => {
                    const props = createMemo(() =>
                      item.trigger ? triggerItemProps() : root().getItemProps({ id: item.id }),
                    )
                    return (
                      <li data-testid={item.id} {...props()}>
                        {item.label}
                      </li>
                    )
                  }}
                </For>
              </ul>
            </div>
          </Portal>

          <Portal>
            <div {...sub().positionerProps}>
              <ul data-testid="more-tools-submenu" class="menu-content" {...sub().contentProps}>
                <For each={level2}>
                  {(item) => {
                    const props = createMemo(() =>
                      item.trigger ? triggerItem2Props() : sub().getItemProps({ id: item.id }),
                    )
                    return (
                      <li data-testid={item.id} {...props}>
                        {item.label}
                      </li>
                    )
                  }}
                </For>
              </ul>
            </div>
          </Portal>

          <Portal>
            <div {...sub2().positionerProps}>
              <ul data-testid="open-nested-submenu" class="menu-content" {...sub2().contentProps}>
                <For each={level3}>
                  {(item) => (
                    <li data-testid={item.id} {...sub2().getItemProps({ id: item.id })}>
                      {item.label}
                    </li>
                  )}
                </For>
              </ul>
            </div>
          </Portal>
        </div>
      </main>

      <Toolbar
        controls={null}
        visualizer={
          <>
            <StateVisualizer state={state} />
            <StateVisualizer state={subState} />
            <StateVisualizer state={sub2State} />
          </>
        }
      />
    </>
  )
}
