// examples/lit-ts/src/main.ts
import { LitElement, html } from "lit"
import { customElement, property } from "lit/decorators.js"
import { routesData } from "@zag-js/shared"

import "@zag-js/shared/src/style.css"
import "./main.css"

// Import toolbar components
import "./components/toolbar"
import "./components/state-visualizer"

// Import all page components
import "./pages/accordion"
import "./pages/dialog"
import "./pages/dialog-nested"
import "./pages/toggle"
import "./pages/toggle-group"
import "./pages/menu"

@customElement("zag-app")
export class ZagApp extends LitElement {
  // Light dom (no shadow root) due to css
  protected createRenderRoot() {
    return this
  }

  @property({ type: String })
  currentPath = window.location.pathname

  connectedCallback() {
    super.connectedCallback()
    this.updatePath()
    window.addEventListener("popstate", this.updatePath)
  }

  disconnectedCallback() {
    super.disconnectedCallback()
    window.removeEventListener("popstate", this.updatePath)
  }

  private updatePath = () => {
    this.currentPath = window.location.pathname
  }

  private navigate(path: string) {
    window.history.pushState({}, "", path)
    this.currentPath = path
  }

  private renderContent() {
    switch (this.currentPath) {
      case "/accordion":
        return html`<accordion-page class="component-page"></accordion-page>`
      case "/dialog":
        return html`<dialog-page class="component-page"></dialog-page>`
      case "/dialog-nested":
        return html`<dialog-nested-page class="component-page"></dialog-nested-page>`
      case "/toggle":
        return html`<toggle-page class="component-page"></toggle-page>`
      case "/toggle-group":
        return html`<toggle-group-page class="component-page"></toggle-group-page>`
      case "/menu":
        return html`<menu-page class="component-page"></menu-page>`
      default:
        return this.renderHome()
    }
  }

  private renderHome() {
    return html`
      <div class="index-nav">
        <h2>Zag.js + Lit</h2>
        <p>Select a component from the sidebar to see it in action.</p>
      </div>
    `
  }

  render() {
    const routes = routesData.filter((route) =>
      // Only show routes we have implemented
      ["/accordion", "/dialog", "/dialog-nested", "/toggle", "/toggle-group", "/menu"].includes(route.path),
    )

    return html`
      <div class="page">
        <aside class="nav">
          <header>Zagjs</header>
          <a
            href="/"
            ?data-active=${this.currentPath === "/"}
            @click=${(e: Event) => {
              e.preventDefault()
              this.navigate("/")
            }}
          >
            Home
          </a>
          ${routes.map(
            (route) => html`
              <a
                href=${route.path}
                ?data-active=${this.currentPath === route.path}
                @click=${(e: Event) => {
                  e.preventDefault()
                  this.navigate(route.path)
                }}
              >
                ${route.label}
              </a>
            `,
          )}
        </aside>
        ${this.renderContent()}
      </div>
    `
  }
}

// examples/preact-ts/src/index.tsx
import { dataAttr } from "@zag-js/dom-query"
import { routesData } from "@zag-js/shared"
import { render } from "preact"
import { LocationProvider, Route, Router, useLocation } from "preact-iso"
import "../../../shared/src/style.css"
import { NotFound } from "./pages/_404.jsx"
import { routes } from "./routes"

export function App() {
  const location = useLocation()
  return (
    <div className="page">
      <aside class="nav">
        <header>Zagjs</header>
        {routesData
          .sort((a, b) => a.label.localeCompare(b.label))
          .map((route) => (
            <a data-active={dataAttr(location.path === route.path)} href={route.path}>
              {route.label}
            </a>
          ))}
      </aside>
      <Router>
        {(routes as any).map((route, index) => (
          <route.component key={index} path={route.path} />
        ))}
        <Route default component={NotFound} />
      </Router>
    </div>
  )
}

render(
  <LocationProvider>
    <App />
  </LocationProvider>,
  document.getElementById("app"),
)
