// examples/svelte-ts/src/routes/toolbar/with-menu/+page.svelte
<script lang="ts">
  import StateVisualizer from "$lib/components/state-visualizer.svelte"
  import Toolbar from "$lib/components/toolbar.svelte"
  import { mergeProps, normalizeProps, portal, useMachine } from "@zag-js/svelte"
  import * as menu from "@zag-js/menu"
  import * as toolbar from "@zag-js/toolbar"
  import "@styles/toolbar.css"
  import "@styles/menu.css"

  const id = $props.id()
  const service = useMachine(toolbar.machine, { id })
  const api = $derived(toolbar.connect(service, normalizeProps))

  const menuService = useMachine(menu.machine, () => ({
    id: `${id}-menu`,
    ids: { trigger: api.getItemId("more") },
    onSelect: console.log,
  }))
  const menuApi = $derived(menu.connect(menuService, normalizeProps))
</script>

<main class="toolbar">
  <div {...api.getRootProps()}>
    <button {...api.getItemProps({ value: "cut" })}>Cut</button>
    <button {...api.getItemProps({ value: "copy" })}>Copy</button>
    <button {...api.getItemProps({ value: "paste" })}>Paste</button>
    <div {...api.getSeparatorProps()}></div>
    <button {...mergeProps(menuApi.getTriggerProps(), api.getItemProps({ value: "more" }))}>
      More actions <span {...menuApi.getIndicatorProps()}>v</span>
    </button>
    {#if menuApi.open}
      <div use:portal {...menuApi.getPositionerProps()}>
        <ul {...menuApi.getContentProps()}>
          <li {...menuApi.getItemProps({ value: "help" })}>Help</li>
          <li {...menuApi.getItemProps({ value: "shortcuts" })}>Keyboard Shortcuts</li>
          <li {...menuApi.getItemProps({ value: "release-notes" })}>Release Notes</li>
        </ul>
      </div>
    {/if}
  </div>
</main>

<Toolbar>
  <StateVisualizer state={service} />
</Toolbar>

// examples/preact-ts/src/pages/toolbar/with-menu.tsx
import { mergeProps, normalizeProps, Portal, useMachine } from "@zag-js/preact"
import * as menu from "@zag-js/menu"
import * as toolbar from "@zag-js/toolbar"
import { useId } from "react"
import { StateVisualizer } from "../../components/state-visualizer"
import { Toolbar as ControlsPanel } from "../../components/toolbar"

function MoreActionsMenu(props: { api: toolbar.Api }) {
  const { api } = props
  const service = useMachine(menu.machine, {
    id: useId(),
    ids: { trigger: api.getItemId("more") },
    onSelect: console.log,
  })
  const menuApi = menu.connect(service, normalizeProps)

  return (
    <>
      <button {...mergeProps(menuApi.getTriggerProps(), api.getItemProps({ value: "more" }))}>
        More actions <span {...menuApi.getIndicatorProps()}>v</span>
      </button>
      {menuApi.open && (
        <Portal>
          <div {...menuApi.getPositionerProps()}>
            <ul {...menuApi.getContentProps()}>
              <li {...menuApi.getItemProps({ value: "help" })}>Help</li>
              <li {...menuApi.getItemProps({ value: "shortcuts" })}>Keyboard Shortcuts</li>
              <li {...menuApi.getItemProps({ value: "release-notes" })}>Release Notes</li>
            </ul>
          </div>
        </Portal>
      )}
    </>
  )
}

export default function Page() {
  const service = useMachine(toolbar.machine, { id: useId() })
  const api = toolbar.connect(service, normalizeProps)

  return (
    <>
      <main class="toolbar">
        <div {...api.getRootProps()}>
          <button {...api.getItemProps({ value: "cut" })}>Cut</button>
          <button {...api.getItemProps({ value: "copy" })}>Copy</button>
          <button {...api.getItemProps({ value: "paste" })}>Paste</button>
          <div {...api.getSeparatorProps()} />
          <MoreActionsMenu api={api} />
        </div>
      </main>

      <ControlsPanel>
        <StateVisualizer state={service} />
      </ControlsPanel>
    </>
  )
}
